/**
 * JANE EYRE - CHAPTER 27
 * 
 * Jane recovers and builds new life with the Rivers family. She accepts work teaching
 * at a village school, finds intellectual companionship with Diana and Mary, receives
 * shocking news of inheritance and family connection, and faces St. John's proposal
 * of marriage without love—all while still thinking constantly of Rochester.
 */

import { ChapterData } from '@/app/lib/types/book.types'
import { getLiteratureMessageByChapter } from '@/app/lib/literature-matters-messages'

export const chapter27: ChapterData = {
  number: 27,
  title: 'New Life and Family Found',
  
  readingTime: 24,
  pages: 16,
  
  // ===================================================================
  // SUMMARY
  // Two-level summary: brief (one sentence) and full (3-4 paragraphs)
  // ===================================================================
  summary: {
    brief: 'Jane builds a new life with the Rivers family—teaching at a village school, befriending Diana and Mary—then receives shocking news: she has inherited a fortune from her uncle John Eyre, and the Rivers siblings are her cousins, making them the family she never knew she had.',
    
    full: [
      'Jane recovers at Moor House and the Rivers family offers her a position: St. John has arranged for her to teach at a village school for poor children. It\'s humble work—vastly different from her governess role at Thornfield, teaching children who can barely read, living in a small cottage, earning minimal income. Jane accepts without hesitation. She chooses meaningful work over status, independence over comfort. The work is hard: the children are difficult, the conditions are poor, the pay is low. But it\'s honest employment that belongs to her, that she earned through her own capabilities, that no one can take away. Jane finds satisfaction in teaching these children, helping them learn despite their poverty and lack of advantages.',
      
      'Jane grows close to Diana and Mary Rivers. They\'re educated, intelligent, passionate about learning—exactly the intellectual companionship Jane has always wanted. They read together, discuss literature and ideas, share their thoughts and dreams. Jane has finally found female friendship based on equality and mutual respect. Diana and Mary are governesses like Jane, understand the precarity and difficulties of women\'s work, sympathize with each other\'s situations. But St. John is different: he\'s impressive—learned, disciplined, dedicated to his religious calling—but also cold, rigid, fanatical about duty. He sees everything through the lens of religious obligation, has no room for human warmth or personal happiness. St. John begins to pay attention to Jane, not romantically but assessingly—he sees her strength, her principles, her capacity for endurance. He starts to view her as potential helpmate for his missionary ambitions.',
      
      'Then shocking news arrives: Jane\'s uncle John Eyre (the same uncle she wrote to before the wedding) has died in Madeira and left her his entire fortune—twenty thousand pounds. Jane is suddenly wealthy, financially independent for life. No more dependence on employment, no more vulnerability to being fired or left without resources, no more precarity. But the news comes with even more shocking revelation: Mr. Briggs the lawyer (who stopped the wedding) explains that John Eyre was brother to Jane\'s mother—and he was also brother to the Rivers\' mother. The Rivers siblings are Jane\'s cousins. She has family—real family, blood relations who have been kind to her even before knowing the connection. Diana, Mary, and St. John are her cousins.',
      
      'Jane is overjoyed. Not about the money—about the family. She\'s been orphaned and alone her entire life; now she has cousins, people who share her blood, real family who actually care about her. Jane immediately insists on sharing the inheritance equally: twenty thousand pounds divided four ways gives each of them five thousand pounds. Diana and Mary will have independence, won\'t need to work as governesses anymore. St. John will have resources for his missionary work. Jane will still be comfortable. She refuses to keep the fortune while her newly discovered family has nothing—she\'d rather have family and moderate wealth than isolation and riches. The Rivers siblings are stunned by her generosity. St. John accepts somewhat reluctantly (he\'s focused on his calling, not money), but Diana and Mary are moved to tears—Jane has given them freedom. This is Jane\'s dream realized: family, community, independence, security. But she still thinks constantly of Rochester—wonders how he is, whether he thinks of her, if she\'ll ever see him again. And St. John is watching her, calculating, beginning to form a plan to make Jane his wife—not from love, but from duty and practicality.'
    ]
  },
  
  // ===================================================================
  // TERMS TO KNOW
  // Literary devices, vocabulary words, and concepts crucial to understanding
  // ===================================================================
  termsToKnow: [
    {
      term: 'Choosing Meaningful Work Over Status',
      definition: 'Accepting humble employment that provides purpose and independence rather than prestigious work that would require compromising your values or depending on others\' approval.',
      context: 'St. John offers Jane work teaching poor children at a village school—far beneath her qualifications and vastly different from being governess to wealthy families. The work is hard, the pay is low, the students are difficult. But Jane accepts immediately and finds satisfaction in it. She chooses meaningful work that\'s truly hers (earned through her own capabilities, can\'t be taken away) over prestigious work that would require depending on others. The humble teaching position gives her independence and purpose, which matters more than status.',
      whyItMatters: 'Sometimes the best work for you isn\'t the most prestigious or lucrative—it\'s what gives you purpose, independence, and alignment with your values. Modern contexts: choosing nonprofit work over corporate career despite lower pay, accepting less prestigious job that allows better work-life balance, taking position that matches values even if it\'s "beneath" your qualifications. Understanding this helps: (1) Define success by what matters to you (purpose, independence, values) not external status markers, (2) Recognize humble work can be more meaningful than prestigious work if it aligns with your principles, (3) Value independence (work you control, that\'s truly yours) over prestige (work that requires pleasing powerful people), (4) Consider whether job gives you what you need (security, purpose, autonomy) regardless of how impressive it sounds to others.'
    },
    {
      term: 'Found Family Becomes Real Family',
      definition: 'Discovering that people who chose to care for you (found family) are actually your biological relatives—the validation that the people who felt like family really are family.',
      context: 'The Rivers siblings saved Jane\'s life when she was a stranger, treated her with kindness and respect, became the community she needed—they were her found family. Then Jane discovers they\'re actually her cousins, her biological family. The people who felt like family really are family. This validates the connection Jane felt, gives her both chosen relationships (they cared for her before knowing the connection) and biological ties (they\'re her actual relatives). She has family who would have been good to her anyway, and who are now revealed to be blood relations.',
      whyItMatters: 'Sometimes the people who feel like family—who choose to care for you with no obligation—turn out to be connected to you in ways you didn\'t know. But more importantly, the story validates that family isn\'t primarily about blood—it\'s about who chooses to care for you. The Rivers were Jane\'s family before she knew they were cousins. Modern contexts: discovering distant relatives among friends, finding biological family that validates chosen family, realizing people who supported you "like family" actually are distantly related. Understanding this helps: (1) Recognize family is defined by care and choice, not just biology, (2) Value relationships for what they are (supportive, caring, meaningful) regardless of biological connection, (3) Appreciate when biological and chosen family overlap, (4) Understand blood doesn\'t make family—consistent care and mutual support does.'
    },
    {
      term: 'Sharing Inheritance: Choosing Family Over Fortune',
      definition: 'When you receive significant resources, immediately sharing them with people you care about rather than keeping everything for yourself—prioritizing relationship and community over personal wealth.',
      context: 'Jane inherits twenty thousand pounds—fortune that makes her independently wealthy for life. But she immediately insists on dividing it equally with the Rivers siblings: five thousand pounds each. She refuses to keep the fortune while her newly discovered family has nothing. Jane would rather have family and moderate wealth than isolation and riches. This shocks the Rivers—most people would keep the inheritance. But for Jane, having family matters more than having maximum money. She chooses community over fortune.',
      whyItMatters: 'How you handle resources reveals what you value. When you receive significant inheritance, windfall, or opportunity, do you immediately share with people you care about, or hoard it for yourself? Jane\'s choice shows she values family/community over maximum personal wealth. Modern contexts: sharing inheritance with siblings despite legal ability to keep it all, using windfall to help family members in need, creating opportunities for others when you succeed. Understanding this helps: (1) Recognize generosity creates stronger relationships than hoarding resources, (2) Consider that enough money plus strong community might be better than maximum money plus isolation, (3) Value what resources enable (family security, shared opportunity) over what you personally accumulate, (4) Build culture of mutual support rather than individual accumulation.'
    },
    {
      term: 'Duty-Based vs. Love-Based Relationships',
      definition: 'Distinguishing between relationships built on mutual care and affection vs. relationships based on practical utility and shared purpose—recognizing when someone wants you for what you can do, not who you are.',
      context: 'St. John begins viewing Jane as potential wife—not because he loves her or feels attracted to her, but because he sees her as useful for his missionary work. He needs strong, disciplined, capable partner for his calling; Jane fits that description. This is duty-based relationship assessment: he evaluates Jane for her utility to his purpose, not for herself as person he cares about. St. John will eventually propose marriage from duty, not love. This contrasts sharply with Rochester, who loved Jane passionately (though problematically), and with Diana and Mary, who value Jane for herself.',
      whyItMatters: 'Some people want you for what you can do for them (help their career, fulfill their goals, support their ambitions) rather than for who you are. Learning to distinguish between: (A) relationships where you\'re valued as person (they care about your happiness, respect your autonomy, love you for yourself), and (B) relationships where you\'re valued as tool (they see your utility, want you to serve their purposes, would replace you if someone more useful came along). Modern contexts: partner who wants spouse to advance their career, boss who values you only for productivity, friend who needs your connections but doesn\'t actually care about you. Understanding this helps: (1) Notice when someone assesses you for utility rather than caring about you as person, (2) Question relationships where everything is about their goals/needs with little regard for yours, (3) Recognize proposal/offer based on what you can provide (skills, connections, resources) rather than who you are, (4) Value relationships where you\'re loved for yourself over relationships where you\'re useful for their purposes.'
    },
    {
      term: 'Independence Through Inheritance: When Luck Changes Everything',
      definition: 'How sudden financial security transforms your options and power—going from vulnerable and dependent to independent and secure through inheritance or windfall.',
      context: 'Before inheritance: Jane was dependent on employment, could be fired and left destitute (nearly happened when she left Rochester), had no security or family support. After inheritance: Jane has financial independence for life, can make choices based on what she wants rather than survival needs, has power to help others. The inheritance transforms Jane\'s situation completely—she goes from precarious to secure, from vulnerable to powerful. This changes what\'s possible for her: she doesn\'t need to accept work she doesn\'t want, doesn\'t need to marry for security, doesn\'t need to compromise her principles to survive.',
      whyItMatters: 'Financial security changes what choices are available to you. When you\'re dependent on income from employment/relationship/family, you have limited options—you must accept what\'s offered or face destitution. When you have financial independence (inheritance, savings, investments, other resources), you can make choices based on values rather than survival. Modern contexts: inheritance that allows career change, windfall that provides freedom to leave bad situation, financial security that enables saying no to compromising opportunities. Understanding this helps: (1) Recognize how financial vulnerability limits choices—many people stay in bad situations because they can\'t afford to leave, (2) Build financial independence when possible (emergency fund, savings, skills that are marketable) to expand your options, (3) Use financial security to make principled choices (Jane can now do work she finds meaningful regardless of pay), (4) Acknowledge role of luck—inheritance and windfalls aren\'t earned, they\'re fortunate, and they shouldn\'t make you judge people who haven\'t received such luck.'
    }
  ],
  
  // ===================================================================
  // CHARACTERS
  // Character development for this chapter
  // ===================================================================
  characters: [
    {
      name: 'Jane Eyre',
      development: 'Jane builds new life at Moor House: accepts humble teaching work and finds satisfaction in it, develops deep friendship with Diana and Mary, discovers she has family and fortune. She\'s transformed from destitute and alone to wealthy and connected—but the money matters less than the family. Jane immediately shares the inheritance because having community matters more than having maximum wealth. She\'s finally achieved security and belonging, but she still thinks constantly of Rochester—wondering about him, missing him, carrying the love that never diminished. This is Jane finding peace and purpose, but not complete happiness because Rochester is absent.',
      keyTrait: {
        emoji: '🏡',
        text: 'Building Home and Family'
      }
    },
    {
      name: 'St. John Rivers',
      development: 'St. John is impressive but cold: dedicated clergyman, learned and disciplined, committed to missionary calling. But he has no warmth, sees everything through lens of religious duty, values utility over human connection. He begins assessing Jane as potential missionary wife—not because he loves her but because she\'s strong, capable, and suited to the work. He views marriage as practical arrangement for serving God, not romantic partnership. St. John represents duty divorced from love, principle without warmth, dedication that becomes fanaticism. He\'ll become Jane\'s next major challenge: resisting loveless marriage proposed from duty.',
      keyTrait: {
        emoji: '❄️',
        text: 'Cold Duty'
      }
    },
    {
      name: 'Diana and Mary Rivers',
      development: 'Diana and Mary are the female friendship and intellectual companionship Jane has always wanted. They\'re educated, intelligent, passionate about ideas and learning. They treat Jane as equal, share interests and conversations, provide genuine friendship. When revealed as Jane\'s cousins, they\'re overjoyed—they gain both family and financial independence (through Jane\'s sharing of inheritance). Diana and Mary represent ideal female relationships: mutual respect, shared intellect, genuine care. They\'re the sisters Jane never had.',
      keyTrait: {
        emoji: '👭',
        text: 'Sisterly Companionship'
      }
    },
    {
      name: 'The Village School Students',
      development: 'Jane\'s students are poor children with limited opportunities: they can barely read, have rough manners, face poverty and hardship. At first Jane finds teaching them difficult—they\'re not like the refined pupils she\'s used to. But she grows to care about them, finds satisfaction in helping them learn despite their disadvantages. The students represent Jane\'s commitment to meaningful work: she could seek more prestigious employment, but she chooses to teach these children who actually need her.',
      keyTrait: {
        emoji: '📚',
        text: 'Humble Pupils'
      }
    },
    {
      name: 'John Eyre (Deceased Uncle)',
      development: 'John Eyre appears only through his legacy: the inheritance he leaves Jane and the family connection he represents. He\'s Jane\'s mother\'s brother, making him the family link Jane never knew she had. His death provides Jane with fortune and reveals her connection to the Rivers. Though he never appears in person (he was in Madeira throughout), his impact on Jane\'s life is profound: he gives her financial independence and family.',
      keyTrait: {
        emoji: '💰',
        text: 'Generous Legacy'
      }
    }
  ],
  
  // ===================================================================
  // KEY QUOTES
  // 3-5 significant quotations with analysis
  // ===================================================================
  quotes: [
    {
      text: 'I will be a village schoolmistress. I will teach the children of the poor. It is humble work, but it is honest work, and it is mine. I am beholden to no one.',
      analysis: 'Jane chooses meaningful work over status. The village school is beneath her qualifications, but it provides independence—work that\'s truly hers, that she earned through her capabilities, that no one can take away. "I am beholden to no one" captures what Jane values: autonomy matters more than prestige. This is Jane prioritizing independence and purpose over social status and comfort. She\'d rather have humble work she controls than prestigious work that requires depending on powerful people\'s approval.'
    },
    {
      text: 'Diana and Mary are my sisters in all but name. Finally, I have found the intellectual companionship, the female friendship I have always wanted. We read together, think together, dream together.',
      analysis: 'Jane has found the relationships she\'s craved: female friendship based on equality and shared intellect. With Diana and Mary, she\'s not servant or dependent; she\'s equal partner in intellectual pursuits. "Sisters in all but name" foreshadows the revelation that they actually are her family. But more importantly, it shows that family is defined by care and mutual respect, not just biology. They were her sisters before she knew they were cousins.'
    },
    {
      text: 'Twenty thousand pounds! I am wealthy. But the money means less to me than the revelation that followed: the Rivers are my cousins. I have family. Real family. I am not alone in the world.',
      analysis: 'Jane values family more than fortune. The inheritance provides security, but the family connection provides belonging. "I am not alone in the world" is what truly matters—Jane has been orphaned and isolated her entire life; now she has blood relations who actually care about her. This shows Jane\'s priorities: she\'d rather have family and moderate wealth than isolation and maximum money. Community matters more than individual accumulation.'
    },
    {
      text: 'I will divide the inheritance equally among the four of us. Five thousand pounds each. I refuse to be rich while my family has nothing. I would rather have cousins and competence than fortune and loneliness.',
      analysis: 'Jane immediately chooses to share the inheritance rather than keeping it all. This shocks the Rivers (most people would keep the fortune) but reveals Jane\'s values: family and community matter more than personal wealth. "Cousins and competence" (family plus enough money to live on) vs. "fortune and loneliness" (maximum wealth but isolation)—Jane chooses relationship over resources. This is radical generosity: she divides the inheritance equally despite having legal right to keep it all.'
    },
    {
      text: 'St. John watches me with calculating eyes. He sees me not as woman but as potential instrument for his missionary work. He assesses my strength, my endurance, my principles—not to love me, but to use me.',
      analysis: 'Jane recognizes that St. John views her as tool for his purposes rather than person to be loved. "Not to love me, but to use me" is crucial distinction: some people want you for what you can do for them (help their goals, serve their purposes) rather than for who you are. St. John will propose marriage, but it will be duty-based (you\'re useful for my calling) not love-based (I care about you as person). Jane notices this assessment, recognizing the difference between being valued and being useful.'
    }
  ],
  
  // ===================================================================
  // IA ANALYSIS (Intelligence Amplifier Analysis)
  // Deep dive into themes and literary techniques
  // ===================================================================
  iaAnalysis: {
    themes: [
      {
        name: 'Meaningful Work Over Status',
        explanation: 'Jane accepts humble teaching position despite being overqualified. The work is hard, the pay is low, the students are difficult—but it provides independence and purpose. Jane chooses meaningful work she controls over prestigious work that would require depending on others. The theme explores: what makes work valuable? Is it status and pay, or autonomy and purpose? Jane demonstrates that work\'s value comes from what it gives you (independence, meaning, alignment with values) not how impressive it sounds.'
      },
      {
        name: 'Family and Fortune: Choosing Community Over Accumulation',
        explanation: 'Jane inherits fortune but immediately shares it equally with the Rivers. She chooses family plus moderate wealth over isolation plus maximum money. This radical generosity reveals Jane\'s priorities: community matters more than personal accumulation. The theme challenges individualistic wealth-hoarding: Jane recognizes that having cousins and competence is better than having fortune and loneliness. She uses resources to strengthen relationships rather than maximize personal wealth.'
      },
      {
        name: 'Duty Without Love: When Someone Wants You for Utility',
        explanation: 'St. John begins viewing Jane as potential missionary wife—not from love but from assessment of her utility to his calling. He sees her strength and capability, not her as person to be cherished. The theme explores dangerous dynamic: relationships where you\'re valued for what you can do (help their goals, serve their purposes) rather than who you are (person deserving love and care). Jane will have to recognize and resist this utilitarian view of relationship.'
      }
    ],
    
    literaryTechniques: [
      {
        name: 'Parallel Humble Beginnings: Village School and Lowood',
        explanation: 'Jane\'s teaching at village school parallels her time at Lowood: both are humble, difficult situations involving education of poor children, both require Jane to find purpose in challenging circumstances, both ultimately provide foundation for growth. But crucial difference: at Lowood Jane was powerless child subjected to harsh treatment; at village school she\'s adult who chose this work, has autonomy and purpose. The parallel shows Jane\'s growth—similar circumstances, but now she\'s agent making choices rather than victim suffering treatment.',
        example: 'Lowood: Poor children, harsh conditions, Jane as student then teacher, finding purpose despite hardship. Village school: Poor children, difficult conditions, Jane as teacher, finding purpose despite humble status. Both involve education in poverty, both require Jane to persist despite difficulty. But: at Lowood she had no choice (orphan sent there), no autonomy (subject to Brocklehurst\'s tyranny), was victim of circumstances. At village school she chooses this work (could seek more prestigious employment), has autonomy (the work is hers, she controls it), is agent making decisions. Same humble circumstances, transformed meaning because of Jane\'s agency.'
      },
      {
        name: 'Contrast Between Rochester and St. John',
        explanation: 'Brontë structures the novel with two male figures representing opposite extremes: Rochester (passion without principle—loved Jane deeply but deceived her, all emotion and desire) and St. John (principle without passion—will propose to Jane from duty, all cold calculation and religious fanaticism). Neither is ideal: Rochester loved but lied; St. John is honest but loveless. The contrast forces question: can you have both passion and principle? Must you choose between love with deception and duty without affection? Jane seeks middle ground: relationship with both genuine feeling and moral integrity.',
        example: 'Rochester: Passionate love, genuine desire for Jane, warmth and emotion—but also deception, attempted bigamy, possessiveness. Felt deeply but acted wrongly. St. John: Honest and principled, dedicated to religious calling, transparent about intentions—but cold, views Jane as tool, proposes marriage from duty not love. Acts correctly but feels nothing. Jane: Seeks both—wants passion WITH honesty, love WITH principle, feeling WITH integrity. Brontë shows extremes are inadequate: Rochester\'s passionate deception nearly destroyed Jane; St. John\'s loveless duty would also destroy her (different way). Only synthesis of passion and principle can work.'
      },
      {
        name: 'Found Family Revealed as Real Family',
        explanation: 'Brontë creates satisfying narrative arc: strangers who chose to save Jane (found family) are revealed to be her biological relatives (real family). This validates both found family (their care before knowing connection shows genuine love) and biological family (Jane isn\'t truly alone, has blood relations). The revelation works emotionally because: (1) Rivers already proved they\'re family through actions—biology just confirms what already existed, (2) Jane gets both chosen relationships and biological ties, (3) It rewards Jane\'s generosity (she would have shared with them as friends; learning they\'re cousins makes sharing even more meaningful).',
        example: 'Structure: First, Rivers save Jane from death (found family—strangers who choose to help with no obligation). Then, Jane builds relationships with them (chosen family—they become important through shared time and mutual respect). Finally, revelation they\'re cousins (real family—biological connection). This order is crucial: if Jane learned they were cousins first, we\'d wonder if their kindness was just family obligation. Learning it after they\'ve already proved their care shows: they would have been good to her anyway. The biology validates the feeling ("they feel like family") without being the source of it ("they\'re only nice because they\'re family"). Brontë gives Jane both: people who chose to love her AND blood relations.'
    }
    ]
  },
  
  // ===================================================================
  // MODERN ADAPTATION
  // Connect the classic text to contemporary life
  // ===================================================================
  modernAdaptation: {
    setting: 'Imagine you\'re rebuilding after leaving bad situation: you have humble job teaching or doing community work, living simply, building new life. You develop genuine friendship with people you work with—intellectual equals who become your chosen family. Then you receive unexpected news: distant relative you barely knew has died and left you significant inheritance—enough for financial security and independence. But there\'s more: the people who became your chosen family turn out to be your biological relatives—distant cousins you never knew about. Suddenly you have both financial independence and real family. You could keep the inheritance (you have legal right), but you immediately decide to share it equally with your newly discovered cousins. Some people think you\'re foolish (you could be rich!), but you\'d rather have family and enough than fortune and isolation. Meanwhile, someone at your work or in your community—impressive, dedicated to important cause, respected by everyone—begins paying attention to you. But it\'s not romantic interest; it\'s assessment of your utility for their goals. They see your skills, work ethic, dedication to principles, and they start viewing you as potential partner for their mission—not because they love you, but because you\'d be useful. They eventually propose committed partnership (business, marriage, collaboration) based on shared goals and complementary skills, not emotional connection or genuine care. They\'re honest about this: "We would work well together, accomplish important things, serve this cause effectively." No deception, but also no love. Do you accept practical partnership with impressive person for meaningful cause? Or do you hold out for relationship that includes both purpose and genuine affection?',
    
    parallels: [
      '🔹 **Choosing Meaningful Work Over Prestige**: Accepting humble job that provides purpose and independence rather than prestigious work that requires compromising values. Modern contexts: nonprofit work over corporate career, teaching in underserved community, work that aligns with values even if less impressive. Recognizing: status matters less than autonomy and meaning.',
      '🔹 **Found Family Becoming Real Family**: People who chose to care for you (no obligation) turning out to be biological relatives. More importantly: validating that family is about care and choice, not just blood. Modern contexts: discovering distant relatives among friends, DNA tests revealing unexpected connections. Understanding: they were family before you knew the biology.',
      '🔹 **Sharing Inheritance/Windfall**: Receiving significant resources and immediately sharing with people you care about rather than hoarding. Modern contexts: splitting inheritance equally despite legal ability to keep more, using windfall to help family/friends, creating opportunities for community. Choosing: family plus enough over fortune plus isolation.',
      '🔹 **Duty-Based vs. Love-Based Relationships**: Distinguishing between partnerships based on utility (you\'re useful for their goals) vs. genuine care (they value you as person). Modern contexts: partner wanting spouse for career advancement, someone proposing because you "fit" their life plan, relationship based on complementary skills not affection. Recognizing: being useful isn\'t same as being loved.',
      '🔹 **Financial Independence Changing Options**: How sudden security (inheritance, windfall, financial stability) transforms what choices are available—going from needing to accept whatever\'s offered to choosing based on values. Modern contexts: inheritance allowing career change, savings providing freedom to leave bad job, financial security enabling principled choices. Understanding: privilege of having options.',
      '🔹 **Intellectual Companionship**: Finding people who share your interests, match your mind, provide stimulating conversation—the friendship that feeds your intellect. Modern contexts: book clubs, discussion groups, colleagues who challenge you intellectually, friends who actually understand your field/interests. Valuing: relationships that engage your mind, not just social connections.',
      '🔹 **Building New Life After Loss**: Reconstructing your life after leaving everything—new work, new community, new routine, new identity. Modern contexts: rebuilding after divorce, starting over after leaving abusive situation, new city/career after major change. Process: it\'s slow, requires intention, involves both loss and growth.'
    ],
    
    discussionPrompt: 'Have you chosen meaningful work over prestigious work? What made you value purpose over status? Have you shared resources (inheritance, windfall, opportunities) with family/friends rather than keeping maximum for yourself? Have you been valued for your utility (skills, connections, what you can do) rather than for yourself? How did you recognize that and respond? Have you found chosen family that became as important as biological family? Have financial constraints limited your options—and if you gained financial security, what would change? How do you distinguish between partnerships built on complementary skills/shared goals vs. partnerships built on genuine affection and care?'
  },
  
  // ===================================================================
  // THEMATIC THREADS
  // Ongoing themes that recur throughout the novel
  // ===================================================================
  thematicThreads: [
    {
      emoji: '🏠',
      name: 'Home as Community, Not Place',
      explanation: 'Jane finally has home—but it\'s not location (Moor House is just house), it\'s the people (Rivers family who care for her, intellectual companionship, belonging). Throughout novel, Jane has sought home: Gateshead (rejected), Lowood (institutional), Thornfield (lost), now Moor House (found). The thread shows: home isn\'t where you live; it\'s where you\'re accepted, where you belong, where people choose to care for you. Jane found home by finding family.'
    },
    {
      emoji: '💰',
      name: 'Financial Independence as Freedom',
      explanation: 'The inheritance transforms Jane\'s situation: she goes from dependent and vulnerable (needing employment to survive, could be fired and destitute) to independent and secure (can make choices based on values not survival). Throughout novel, Jane\'s lack of resources has limited her options; now financial independence expands what\'s possible. But thread also shows: money alone isn\'t enough—Jane values family more than fortune, chooses community over maximum wealth.'
    },
    {
      emoji: '❄️🔥',
      name: 'Cold Duty vs. Passionate Love',
      explanation: 'St. John represents opposite extreme from Rochester: where Rochester was all passion (loved deeply but deceived), St. John is all duty (honest but loveless). Neither extreme is adequate: Rochester\'s passionate deception nearly destroyed Jane; St. John\'s loveless duty would also destroy her (differently). Jane seeks synthesis: relationship with both genuine feeling and moral integrity. Can she have passion WITH honesty, love WITH principle?'
    },
    {
      emoji: '👭',
      name: 'Female Friendship and Intellectual Companionship',
      explanation: 'Diana and Mary provide what Jane has always wanted: female friendship based on equality, shared intellect, mutual respect. Jane finally has relationships with women who are equals (not servants like Bessie, not superiors like Miss Temple, not students like Adèle), who share her interests and match her mind. This thread shows importance of intellectual companionship among women, friendship that engages mind as well as heart.'
    },
    {
      emoji: '👻',
      name: 'Rochester\'s Haunting Absence',
      explanation: 'Though Rochester doesn\'t appear, he haunts this chapter: Jane thinks of him constantly, wonders about him, still loves him despite everything. She\'s building new life—work, friends, family, security—but Rochester\'s absence is profound presence. Jane hasn\'t forgotten him, hasn\'t stopped loving him, hasn\'t moved on. The thread maintains tension: Jane has found peace but not complete happiness because the person she loves is absent.'
    }
  ],
  
  // ===================================================================
  // DISCUSSION QUESTIONS
  // Open-ended questions for classroom or personal reflection
  // ===================================================================
  discussionQuestions: [
    {
      title: 'Meaningful Work vs. Prestigious Work',
      question: 'Jane accepts humble village teaching position despite being overqualified—she chooses meaningful work that provides independence over prestigious work that would require depending on powerful people. When should you take work beneath your qualifications? How do you balance: (A) need for status and recognition, (B) desire for meaningful purpose, (C) requirement for financial security? Is Jane wise to prioritize independence and meaning, or should she seek more prestigious employment that would use her full capabilities?'
    },
    {
      title: 'Sharing Inheritance',
      question: 'Jane immediately divides her inheritance equally with the Rivers siblings—she chooses family plus moderate wealth over isolation plus maximum money. Was this wise? Should she have kept more for herself? What would you do if you inherited significant fortune and had family/friends who needed resources? How do we balance: (A) securing our own future (keeping resources for ourselves), (B) helping people we care about (sharing resources), (C) avoiding creating dependence (giving people fish vs. teaching to fish)?'
    },
    {
      title: 'Duty Without Love',
      question: 'St. John begins viewing Jane as potential missionary wife—not from love but from assessment of her utility to his religious calling. Is it ethical to propose partnership (marriage, business, collaboration) based on complementary skills and shared goals rather than emotional connection? Can duty-based relationships work? Should Jane accept proposal from impressive person for meaningful cause even without love? Or should she hold out for relationship that includes both purpose and genuine affection?'
    },
    {
      title: 'Found Family vs. Biological Family',
      question: 'The Rivers saved Jane\'s life before knowing she was their cousin—they proved they were family through actions before learning biology confirmed it. What makes someone family: biological connection, consistent care, or both? When found family (people who choose you) and biological family (blood relations) conflict, which matters more? What does Jane\'s story suggest about whether family is primarily about blood or about choice and care?'
    },
    {
      title: 'Financial Independence Changing Options',
      question: 'Before inheritance, Jane needed employment to survive and had limited options. After inheritance, she can make choices based on values rather than survival needs. How does financial security expand what choices are available? Is it fair that people with resources have options people without resources lack? What responsibilities come with financial independence that resulted from luck (inheritance, windfall) rather than personal effort?'
    },
    {
      title: 'Intellectual Companionship',
      question: 'Jane finds profound satisfaction in intellectual friendship with Diana and Mary—they read together, discuss ideas, share thoughts. How important is intellectual compatibility in friendships and romantic relationships? Can you have fulfilling relationship without intellectual companionship? Is matching minds as important as matching hearts? What makes intellectual friendship different from social friendship?'
    },
    {
      title: 'Still Thinking of Rochester',
      question: 'Jane is building new life—work, family, security—but she still thinks constantly of Rochester, still loves him despite everything. Should she try to move on? Is it healthy to carry love for someone you had to leave? Does continuing to think about Rochester prevent Jane from fully embracing her new life? Or is it natural (even beautiful) to continue loving someone even when you can\'t be with them?'
    }
  ],
  
  // ===================================================================
  // AMPLIFIED DISCUSSION
  // Deep-dive answers to complex questions
  // ===================================================================
  amplifiedDiscussion: [],
  
  // ===================================================================
  // EDUCATOR RESOURCES
  // Practical classroom tools
  // ===================================================================
  educatorResources: {
    writingPrompt: {
      title: 'Analyzing Duty-Based vs. Love-Based Relationships: Utility vs. Care',
      description: 'Write an analytical essay examining difference between relationships where you\'re valued for utility (what you can do) vs. relationships where you\'re valued as person (who you are), using St. John\'s assessment of Jane as case study. Part 1: Analyze St. John\'s view of Jane. He sees: (A) Her strength and endurance (she survived near-death on moors, rebuilt her life), (B) Her principles and dedication (she maintains integrity despite cost), (C) Her capabilities (intelligent, educated, competent). He concludes: Jane would make excellent missionary wife—strong enough for hardship, principled enough for calling, capable enough to be useful partner. But notice what he doesn\'t see: Jane as person deserving love, Jane\'s need for affection and warmth, Jane\'s own dreams and desires separate from his mission. He assesses her utility, not her personhood. Map evidence: specific moments where St. John evaluates Jane as potential tool vs. moments where Diana/Mary value Jane as person they care about. Part 2: Distinguish between: (A) Complementary skills relationship (we work well together, have shared goals, complement each other\'s strengths—but relationship is primarily functional), (B) Genuine care relationship (we love each other, value each other\'s happiness, care about each other as people—relationship is primarily emotional), (C) Ideal synthesis (both functional and emotional—we work well together AND genuinely care about each other). St. John offers Type A (complementary skills, shared mission, no genuine affection). Rochester offered Type B (genuine love, but dysfunctional and deceptive). Jane seeks Type C (both). Part 3: Apply to contemporary contexts. Present scenarios: (1) Partner proposes because you "fit" their life plan (want spouse, you check boxes) not because they\'re in love with you, (2) Job offer emphasizing how you\'d be perfect for role with no interest in what you want from career, (3) Friendship based on what you can do for them (connections, skills, resources) not who you are, (4) Family member who values you for helping family business/caring for parents/providing resources but doesn\'t actually care about your wellbeing. For each: How do you recognize utility-focused relationship? What red flags indicate someone values what you can do more than who you are? Part 4: Develop framework for evaluating whether relationship values you as person vs. values you as tool. Questions to ask: (A) Does this person care about my happiness separate from what I provide them? (B) Would they still want relationship if I couldn\'t provide the utility they seek? (C) Do they know/care about my dreams, fears, needs beyond how they relate to shared goals? (D) Is relationship primarily about what I can do (help their mission, advance their goals, provide resources) or about mutual care and support?',
      purpose: 'This prompt develops crucial skill: distinguishing between relationships where you\'re genuinely valued vs. relationships where you\'re useful. Students analyze St. John\'s utilitarian view of Jane (she\'d be good missionary wife based on capabilities, not because he loves her), learn to recognize when someone assesses you for utility rather than caring about you as person, develop framework for evaluating whether relationships are based on genuine care or practical benefit. Connects to real life: many people face proposals/offers based on what they can provide (skills, connections, resources) rather than who they are—learning to recognize this protects from relationships where you\'re tool rather than cherished partner. Understanding: (1) How to spot when someone values your utility more than your personhood (they focus on what you can do, show little interest in what you need/want), (2) Difference between complementary partnership (functional, based on shared goals) and caring relationship (emotional, based on mutual love), (3) Red flags that relationship is utility-focused (everything about their needs/goals, they\'d replace you if someone more useful came along), (4) Why genuine care matters—relationships built only on utility fall apart when you can no longer provide what they wanted, while relationships built on care sustain through changes in circumstances.'
    },
    
    activity: {
      title: 'Resource Allocation Simulation: Inheritance Sharing Decisions',
      description: 'Students work through scenarios where they must decide how to allocate windfall or inheritance, exploring tension between keeping maximum for self vs. sharing with family/community. Setup: Divide class into small groups. Each group receives scenario: "You inherit $100,000 from distant relative. Your family situation is: [provide details—siblings in debt, parents struggling, cousins who helped you when struggling, etc.]. You could keep entire inheritance (legal right), or share some/all with family. Decide what to do." Groups must: (1) List who has claim/need (legal claim: you inherited it; emotional claim: family helped you in past; practical claim: family members in genuine need), (2) Consider arguments for keeping (secure your own future, you didn\'t ask for their help, giving creates dependence) vs. sharing (family needs it, you\'d be selfish to hoard when they struggle, building community matters more than personal maximum), (3) Make decision about allocation (keep all, keep most and share some, split equally, give most away, etc.), (4) Justify decision using ethical framework. Each group presents their decision and reasoning. Class discusses: What factors influenced decisions? Did most keep or share? How did different ethical frameworks (consequentialist: what produces best outcomes?; deontological: what\'s right regardless of outcomes?; virtue ethics: what does good person do?; care ethics: what strengthens relationships?) lead to different conclusions? Then reveal: this was based on Jane\'s situation—she inherited £20,000 and immediately split equally four ways (£5,000 each) with newly discovered cousins. Compare students\' decisions to Jane\'s. Was she too generous? Right balance? Not generous enough? Debrief explores: (A) Tension between securing your own future and helping others, (B) How relationship affects obligation (strangers vs. family vs. people who helped you), (C) Whether equal split is fair (you inherited it vs. family is family), (D) Role of having "enough" (Jane with £5,000 is comfortable; does having enough change obligation to share?). Extension: Research wealth distribution, inheritance patterns, charitable giving norms. How do real people handle windfalls? What do different cultural/religious traditions teach about sharing resources? What would create strongest communities—individual accumulation or resource sharing?',
      materials: 'Inheritance scenario cards, resource allocation worksheets, ethical framework guides, decision trees, family situation descriptions, Jane Eyre Chapter 27 excerpts for comparison'
    },
    
    crossCurricular: {
      title: 'Economics/Ethics: Financial Independence and Choice Architecture',
      description: 'Partner with economics/ethics to examine how financial resources expand available choices, using Jane\'s inheritance as case study. Economics class covers: (1) Concept of financial independence (having resources sufficient to meet needs without current employment—investments, savings, passive income, inheritance), (2) How financial security changes options (can choose work based on meaning not just income, can leave bad situations, can make principle-based decisions, can help others), (3) Wealth inequality and access to choices (people with resources have options people without lack—ability to decline unfair offers, freedom to pursue education/training, capacity to take risks), (4) Different sources of financial security (earned through labor vs. inherited vs. windfall vs. social safety nets) and implications of each. Ethics class examines: (A) Is it fair that luck (inheritance, being born to wealthy family, windfalls) creates such different opportunity sets? (B) What obligations come with unearned wealth (inheritance you didn\'t work for—should you share it, use it for social good, treat it differently than money you earned?), (C) How does financial vulnerability limit moral choices (if you can\'t afford to quit unethical job, can you be blamed for staying?), (D) What would just society look like (should everyone have baseline financial security so ethical choices don\'t require risking starvation?). English class analyzes Jane Eyre through this lens: Before inheritance Jane was vulnerable—needed employment to survive, couldn\'t afford to maintain principles if it meant destitution (nearly died on moors after leaving Rochester). After inheritance Jane has options—can choose work based on meaning, can share with family, can make principle-based decisions without survival threat. Understanding how resources created options helps students see: (1) Jane\'s pre-inheritance moral courage was genuinely risky (maintaining principles nearly killed her), (2) Inheritance didn\'t make her more moral, but it made moral choices safer, (3) We should admire moral courage more when person lacks safety net, (4) Creating social safety nets allows more people to act ethically without dying. Final project: Students design economic system that would expand everyone\'s choices, not just wealthy. What combination of (A) minimum income/wealth, (B) social safety nets (health care, housing, food security), (C) educational access, (D) worker protections would allow people to make principle-based choices without risking destitution? Proposal should address: How do you fund this? What are costs/benefits? How does it compare to current system? Would Jane have been able to leave Rochester safely if these structures existed in Victorian England?',
      subjects: ['Economics', 'Ethics', 'Policy', 'Sociology', 'Political Philosophy', 'Social Justice']
    }
  },
  
  // ===================================================================
  // CRITICAL THINKING EXERCISE
  // One focused, high-level analytical task
  // ===================================================================
  criticalThinkingExercise: {
    title: 'Evaluating Utility-Based Relationships: When You\'re Valued for What You Do, Not Who You Are',
    prompt: 'St. John begins viewing Jane as potential missionary wife—assessing her strength, capabilities, suitability for his calling—not because he loves her but because she\'d be useful for his mission. Your task: Analyze the ethics and pragmatics of utility-based relationships (where partnership is based on complementary skills and shared goals rather than emotional connection). Consider: (1) Can duty-based relationships work? Are they ethical? (2) How do you distinguish between valuing someone\'s contributions (appreciating what they bring) vs. valuing them only for utility (seeing them as tool for your purposes)? (3) What are benefits and costs of partnerships built on function rather than affection? (4) Should Jane accept St. John\'s eventual proposal (marriage based on shared mission and complementary capabilities) even without love?',
    
    guidingQuestions: [
      'Map what St. John sees in Jane vs. what Rochester saw vs. what Diana/Mary see. St. John: Evaluates Jane\'s strength (survived near-death), discipline (maintains principles), capabilities (intelligent, competent), suitability for missionary work (could endure hardship). He sees useful partner for his calling—someone who won\'t complain, will support his mission, can handle difficult conditions. He doesn\'t see: Jane as person deserving love, her need for warmth and affection, her dreams separate from his mission, her personhood beyond utility. Rochester: Saw Jane as person he desired—loved her mind, her spirit, her character. Wanted her for herself, not for what she could do for him. But: also saw her as possession to acquire, someone to complete him, object of his desire. Diana/Mary: See Jane as friend they value—appreciate her intellect, enjoy her company, care about her happiness. They value her as person, not for utility. Question: Which view of Jane is healthiest? Rochester loved but possessed; St. John needs but doesn\'t love; Diana/Mary care without agenda. Is Jane safest with people who value her without needing anything from her?',
      'Analyze potential benefits of utility-based relationships. Argument for: (1) Clarity (no confusion about whether it\'s love or practicality—St. John will be honest that it\'s duty not romance), (2) Shared purpose (partnership built on meaningful goals rather than just emotional attraction), (3) Complementary strengths (each person contributes what they\'re good at, efficient division of labor), (4) Stability (not dependent on fluctuating emotions—commitment is to mission not to feelings). St. John would offer Jane: Important work (missionary service), Clear purpose (serving God), Partnership with impressive person (respected, dedicated, principled), Honest terms (he won\'t pretend to love her—no deception). Some people might prefer this: Clear expectations, meaningful work, no pretense. Why is Jane hesitant?',
      'Analyze costs of utility-based relationships. Argument against: (1) You\'re tool not partner (replaceable if someone more useful comes along), (2) Your needs/desires matter only insofar as they serve shared goal (no room for wants that don\'t advance mission), (3) Relationship becomes transaction (I provide this, you provide that, mutual utility) rather than bond (we care about each other beyond what we offer), (4) Love and warmth are missing (intimacy without affection, commitment without tenderness). St. John would NOT offer Jane: Genuine love, Emotional warmth, Interest in her happiness beyond mission, Flexibility for her dreams/desires separate from his calling. Jane would become: Helper for his work, Supporter of his mission, Useful partner, NOT: Beloved wife, Cherished person, Partner whose happiness matters equally. Question: Is marriage without love but with shared purpose better than no marriage? Or is loveless marriage (even with meaningful work) ultimately soul-crushing?',
      'Distinguish between appreciating contributions vs. valuing only for utility. Healthy relationship: "I love you AND I appreciate what you bring to our partnership" (person is valued first, contributions are bonus). Unhealthy relationship: "I value what you bring to our partnership THEREFORE I want relationship with you" (contributions are primary, person is means to end). St. John: Type 2 (unhealthy)—wants Jane BECAUSE she\'d be useful missionary wife. If she weren\'t suitable for mission, he wouldn\'t want her. Rochester: Type 1 (healthy in this dimension, unhealthy in others)—loved Jane for herself, appreciated her character and mind, but also had issues (possessiveness, deception). Questions to evaluate any relationship: (A) Would they still want you if you couldn\'t provide what they currently find useful? (B) Do they care about your happiness separate from how it affects shared goals? (C) Could you be replaced by someone equally useful, or are you irreplaceable as specific person they love?',
      'Apply to contemporary contexts. Scenario 1: Business partner proposes marriage: "We work perfectly together, have compatible goals, would be efficient household. We don\'t love each other, but we respect each other and make good team. Should we marry?" Evaluate: Practical benefits (household efficiency, combined resources, clear goals) vs. emotional costs (loveless intimacy, no romance, risk of resenting practical arrangement). Scenario 2: Career-focused person seeks spouse: "I need partner who can host business events, manage household, support my ambitions. You\'re perfect for this role. Interested?" Evaluate: Is this different from St. John? At least it\'s honest about being transactional—is that better or worse? Scenario 3: Parent wants child to take over family business: "You\'re capable, family needs you, it\'s your duty. Your dreams of different career are less important than family obligation." Evaluate: When does duty-based obligation become suppression of individual desires? Where\'s line between legitimate responsibility and being used? For each scenario: Would you accept utility-based relationship? Under what circumstances is it reasonable vs. when is it ethically problematic?'
    ],
    
    thinkingFramework: {
      analyze: 'Analyze utility-based relationships through framework of what\'s being valued. Dimension 1: What\'s primary basis of relationship? (A) Mutual affection and care (we love each other, want each other\'s happiness, value each other as people)—emotion-based. (B) Shared goals and complementary skills (we work well together, have common purpose, each contribute useful capabilities)—function-based. (C) Combination (we care about each other AND work well together, both love and practical partnership)—ideal synthesis. St. John offers: Type B (function-based with no affection). Rochester offered: Type A (emotion-based but dysfunctional and deceptive). Jane seeks: Type C (both emotion and function). Dimension 2: What happens if utility diminishes? In emotion-based relationship: if you become ill, lose capabilities, change careers—partner still loves you because relationship is about who you are, not what you do. In function-based relationship: if you can\'t provide the utility anymore—what holds relationship together? If St. John married Jane for missionary work and she became unable to do that work, would marriage persist? In synthesis relationship: both functions would hold it together—even if practical utility diminishes, emotional bond persists. Dimension 3: Whose needs/desires matter? In healthy relationship: both partners\' happiness matters; relationship negotiates between "what I need" and "what you need" to find solutions serving both. In utility-based relationship: shared goal matters most; individual needs/desires matter only insofar as they serve goal. St. John framework: Jane\'s needs/desires matter if they make her better missionary wife (she needs enough rest to work effectively) but not if they conflict with mission (she wants different work, warmer climate, gentler lifestyle—too bad, mission comes first). This is fundamental issue: In utility-based relationship, you exist to serve the goal; in care-based relationship, the relationship exists to serve both people.',
      evaluate: 'Evaluate through multiple perspectives. Perspective 1: Pragmatic/consequentialist. Utility-based relationships produce outcomes: shared goals get accomplished, clear expectations prevent disappointment, efficiency of complementary skills. If missionary work is genuinely important (saving souls, serving God, helping people), isn\'t it reasonable to structure marriage to maximize effectiveness of that work? St. John could argue: Individual happiness matters less than mission\'s importance. Jane would be useful missionary wife, they\'d accomplish good together, that justifies functional partnership without romance. Counterargument: Even if mission is important, treating Jane as tool rather than person to be cherished is using her as means to end (Kantian problem—people are ends in themselves, not tools for purposes). Also: Would Jane actually be effective missionary if she\'s loveless and resentful? Perspective 2: Care ethics. Relationships should be built on mutual care, not mutual utility. What matters is whether partners value each other\'s wellbeing, happiness, flourishing—not whether they work well together. St. John fails this: he doesn\'t care about Jane\'s happiness except as it affects her usefulness. Jane would be emotionally starved, working tirelessly for mission while receiving no affection or warmth. This harms her even if mission succeeds. Counterargument: Maybe some people don\'t need romantic love? If Jane didn\'t desire warmth and affection, if she genuinely wanted only purposeful work, would St. John\'s offer be acceptable? Problem: Jane DOES desire love (she loved Rochester, still does—she\'s not aromantic person who doesn\'t need affection). Perspective 3: Virtue ethics. What does virtuous person do? Marrying someone you don\'t love, treating person as tool for your mission, expecting them to sacrifice their desires for your calling—none of this exemplifies virtue. St. John might be dedicated to his calling, but his willingness to use Jane shows lack of respect for her personhood. Virtuous approach would be: "I admire you and think we\'d work well together, but I couldn\'t ask you to marry me without love—you deserve to be cherished, not just useful." Most compelling: Care ethics perspective. Even if utility-based relationships have practical benefits, treating person as tool rather than beloved partner harms them and is ethically wrong. Jane deserves to be loved for herself, not valued for her utility.',
      synthesize: 'Synthesize framework for evaluating whether relationship values you as person vs. values you as tool. Red flags that relationship is utility-focused: (1) Person is more interested in what you can do than who you are (asks about skills, connections, capabilities more than dreams, fears, desires), (2) Your value to them is conditional on providing utility (if you couldn\'t do the thing they need, would they still want you?), (3) Your needs/happiness matter only as they serve shared goal (you need rest because it makes you more effective, not because they care if you\'re tired), (4) You\'re replaceable (if someone equally capable came along, would they prefer that person? or are you irreplaceable because they love YOU specifically?), (5) Relationship framed as partnership/team/collaboration rather than love/affection/care, (6) They\'re honest that it\'s pragmatic not romantic (this is actually good—at least not deceptive—but confirms utility basis). Questions to ask about any relationship proposal: Question 1: "Would you still want this relationship if I couldn\'t provide [the utility you currently see in me]?" If answer is no or hesitant, relationship is utility-based. Question 2: "Do you care about my happiness separate from how it affects our shared goals?" If answer focuses on goals rather than your wellbeing, utility-based. Question 3: "What do you love about me as person, beyond what I can do for you/us?" If they struggle to answer or only cite capabilities/contributions, utility-based. Question 4: "If someone more capable came along, would you prefer them?" Harsh question, but revealing—if you\'re replaceable by anyone who could do job better, you\'re tool not beloved partner. Decision framework: If relationship is primarily utility-based (most answers indicate you\'re valued for contributions not personhood): Option A: Accept it with eyes open (understand you\'re entering pragmatic partnership, not romantic love—make sure that\'s what you want). Option B: Decline and wait for relationship that values you as person (worth being alone rather than being tool, even tool for good cause). Option C: Negotiate for synthesis (acknowledge practical benefits but require genuine care and mutual happiness to be prioritized alongside shared goals). Jane will eventually face this choice with St. John: accept missionary marriage without love (Option A—practical partnership for good cause), decline and maintain independence (Option B—she\'d rather be alone than in loveless marriage), or find third option (Option C—return to Rochester, seek relationship with both love and principle). Apply broadly: When someone wants relationship with you, evaluate whether they value you as person or value what you can provide. Don\'t accept relationships where you\'re tool, even tool for good cause—you deserve to be cherished, not just useful.'
    },
    
    expectedDepth: 'Strong responses will: (1) Distinguish between appreciating someone\'s contributions (healthy) vs. valuing them only for utility (unhealthy)—difference is whether person is valued first with contributions as bonus, or contributions are primary with person as means to get them; (2) Analyze both benefits (clarity, shared purpose, complementary skills, stability) and costs (being tool not partner, needs matter only as they serve goals, lovelessness, replaceability) of utility-based relationships; (3) Map what St. John sees in Jane (strength, capabilities, suitability for mission) vs. what he doesn\'t see (her personhood, her need for love, her desires separate from his calling)—recognize he\'s assessing her as potential tool; (4) Evaluate through multiple ethical frameworks (consequentialist: does mission\'s importance justify functional marriage?, care ethics: relationships should be about mutual care not utility, virtue ethics: using person as tool isn\'t virtuous) and recognize care ethics argument is most compelling; (5) Develop framework for recognizing utility-focused relationships (red flags: more interested in what you do than who you are, conditional value, replaceability, needs matter only as they serve goals); (6) Apply to contemporary contexts (business partner marriage proposal, career-focused person seeking useful spouse, family obligation suppressing individual dreams)—evaluate when utility-based relationships might be acceptable vs. when they\'re ethically problematic; (7) Connect to Jane\'s situation: she left Rochester (loved but deceived), now faces St. John (honest but loveless), seeks synthesis (both love and integrity); (8) Recognize that even honest, duty-based proposal (St. John won\'t lie about it being pragmatic not romantic) is ethically problematic because it treats Jane as tool for his mission rather than person deserving love. Excellent responses will synthesize: Being valued for utility (even utility toward good cause) is fundamentally different from being loved as person; duty-based relationships lack essential element of genuine care; Jane deserves both passionate love AND honest partnership, not one or the other; St. John\'s eventual proposal will be test of whether Jane can resist being useful over being loved.',
    
    classroomApplication: 'Works as: (1) Analytical essay (12-15 pages) examining utility-based vs. care-based relationships, analyzing St. John\'s assessment of Jane, developing framework for recognizing when you\'re valued as tool vs. person; (2) Debate: "Pragmatic marriages based on shared goals and complementary skills are better than romantic marriages based on passion" (argue for: clarity, purpose, stability, efficiency; argue against: lovelessness, being tool not partner, emotional starvation, fundamental disrespect for personhood); (3) Case study analysis: present scenarios where people must decide between utility-based relationships (practical benefits but no love) vs. waiting for care-based relationships (genuine affection but might not come)—students evaluate using framework; (4) Role play: students argue St. John\'s position (pragmatic marriage for important mission) and Jane\'s position (refusing to be tool even for good cause), then switch sides to understand both perspectives; (5) Literature comparison: analyze other texts with utility-based relationships (arranged marriages for family benefit, business partnerships that become romantic, relationships where one person is clearly using the other)—distinguish between functional partnerships that work vs. those that harm. Time: 6-7 class periods including analysis of St. John\'s character, ethics of utility-based relationships, framework development, contemporary applications. Connect to: philosophy (Kant\'s categorical imperative about treating people as ends not means), ethics (care ethics vs. consequentialism), psychology (attachment theory, what makes relationships satisfying), sociology (arranged marriages in different cultures, historical shifts from practical to romantic marriage). Consider inviting: relationship therapist to discuss utility-focused dynamics, person in arranged marriage to share experience, ethicist to discuss when pragmatic relationships are acceptable. Extension: Research: (A) How have marriage norms changed (from primarily economic/political arrangements to romantic partnerships), (B) Do cultures with arranged marriages report different satisfaction than cultures with romantic choice?, (C) What makes relationships satisfying (is love necessary or can shared purpose suffice?). Final reflection: Would you accept relationship based on complementary skills and shared goals but without romantic love? Under what circumstances? What do you need from partnership—practical support, emotional connection, both? How do you distinguish between valuing someone\'s contributions (healthy appreciation) and valuing them for contributions (unhealthy utility-focus)?'
  },
  
  // ===================================================================
  // WHY LITERATURE MATTERS
  // Rotating message about literature's importance (auto-rotated by chapter number)
  // ===================================================================
  whyLiteratureMatters: getLiteratureMessageByChapter(27),
  
  // ===================================================================
  // NEXT TIME TEASER
  // Preview of next chapter to build anticipation
  // ===================================================================
  nextTimeTeaser: {
    emoji: '💍❄️',
    title: 'Next Time: Chapters 28-35 — St. John\'s Proposal and Jane\'s Return',
    preview: 'St. John proposes marriage to Jane—but it\'s not a romantic proposal. He\'s honest: he doesn\'t love her, he needs a missionary wife, she\'s suitable for the work. He proposes duty-based marriage: they\'ll go to India together, serve God, accomplish important work—no love, no warmth, just shared purpose. Jane is tempted: meaningful work, important cause, partnership with impressive man. But she recognizes the cost: lifelong loveless marriage, emotional starvation, being tool for his mission rather than cherished partner. She struggles with the decision: should she accept purposeful partnership even without love? St. John pressures her intensely, using religious language and moral obligation—making her feel selfish for wanting love, guilty for refusing God\'s calling (channeled through him). Jane is close to giving in when something extraordinary happens: she hears Rochester\'s voice calling to her across the distance. It\'s not physical voice—it\'s psychic connection, supernatural summons, the bond between them manifesting impossibly. Jane responds to the call: she decides to find Rochester, discover what\'s happened to him, see if reconciliation is possible. She travels back to Thornfield and finds it burned down—destroyed by fire set by Bertha, who died in the flames. Rochester was injured trying to save her: he\'s blind, has lost a hand, lives in isolation at Ferndean. Jane finds him, and their reunion is profound: he\'s humbled by suffering, she\'s strengthened by independence. Finally they meet as equals: Jane has fortune and family, Rochester has lost his physical power. They can marry now—legally (Bertha is dead) and morally (on equal terms). Jane chooses Rochester: love AND integrity, passion AND principle. She marries him by choice, not necessity, as independent equal, not dependent subordinate.',
    hookQuestion: 'Will Jane accept St. John\'s loveless proposal, or will she resist the pressure and hold out for genuine love? Can she find Rochester? What has happened to him during their separation? And can they build relationship on equal terms after so much has changed?'
  }
}

