/**
 * JANE EYRE - CHAPTER 26
 * 
 * Jane flees Thornfield in the night, leaving everything behind. With almost no money,
 * she travels as far as she can, then wanders the moors starving and desperate. Just
 * when she's about to die of exposure, she collapses at Moor House and is saved by
 * the Rivers family, beginning a new chapter of her life.
 */

import { ChapterData } from '@/app/lib/types/book.types'
import { getLiteratureMessageByChapter } from '@/app/lib/literature-matters-messages'

export const chapter26: ChapterData = {
  number: 26,
  title: 'Flight from Thornfield',
  
  readingTime: 20,
  pages: 14,
  
  // ===================================================================
  // SUMMARY
  // Two-level summary: brief (one sentence) and full (3-4 paragraphs)
  // ===================================================================
  summary: {
    brief: 'Jane flees Thornfield in the depths of night, taking almost nothing, and travels until her money runs out—then wanders the moors for days, begging for food and sleeping rough, until she collapses from starvation and exposure at the doorstep of Moor House, where the Rivers family saves her life.',
    
    full: [
      'In the early morning darkness, while Rochester sleeps, Jane leaves Thornfield. She takes almost nothing—a small bag with a few clothes, her savings (which amount to very little), no food. She knows if she sees Rochester again her resolve might break, so she slips away silently. She walks to the road and catches the first coach heading away from Thornfield. She tells the driver to take her as far as her money will go. The coach travels all day, stopping at villages, carrying Jane farther and farther from everything she knows. When her money runs out, the coach leaves her at a crossroads in the middle of nowhere—moors stretching in all directions, no houses visible, evening falling. Jane has nowhere to go, no money, no plan. She walked away from the only home she had to preserve her integrity, and now she faces the consequences: potential death from exposure and starvation.',
      
      'For days Jane wanders the moors. She tries to find work—knocking on farmhouse doors, asking at shops, offering to do anything for food and shelter. Everyone turns her away. She has no references (can\'t use Thornfield—what would Rochester say if asked?), no connections, nothing to prove her respectability. She looks desperate, suspicious, possibly criminal. She begs for food—most refuse, a few give her scraps. She sleeps outside—under hedges, in doorways, anywhere she can find shelter. She\'s cold, hungry, exhausted, increasingly weak. This is what principle costs: she left Rochester to maintain her integrity, and now she\'s dying slowly on the moors. She thinks of him constantly—wonders if leaving was right choice or terrible mistake, imagines him searching for her (is he? or has he accepted her departure?), questions whether the life she refused (mistress at Thornfield) would have been worse than this death.',
      
      'On what she thinks might be her last night alive, Jane sees lights in the distance. She drags herself toward them—a house, windows lit, smoke from chimney. She approaches: Moor House, isolated dwelling on the moors. Through the window she sees two young women reading together, a servant, comfortable domesticity. She knocks on the door. The servant, Hannah, answers but refuses to let her in—Jane looks like vagrant, possibly dangerous, Hannah won\'t admit stranger. Jane begs: she\'s dying, please help, just let her rest somewhere warm. Hannah refuses, shuts the door. Jane collapses on the doorstep. She\'s about to die here, refused charity, alone in the darkness. This is where choosing principle has led: death on a stranger\'s doorstep.',
      
      'A man returns to the house—St. John Rivers, the brother of the two women Jane saw. He finds Jane collapsed, overrides Hannah\'s objections, carries Jane inside. The Rivers siblings—St. John, Diana, and Mary—nurse Jane back to health. She\'s been near death from starvation and exposure; they feed her carefully, let her rest, ask few questions. As Jane recovers over the next days, she learns about the Rivers family: they\'re educated but poor, their father died recently leaving them almost nothing, the sisters are governesses (like Jane), St. John is a clergyman. They\'re kind, intelligent, principled people. Jane tells them almost nothing about herself—doesn\'t mention Rochester, Thornfield, the interrupted wedding. She says her name is Jane Elliott (half-truth—Eyre-Elliott), that she left her previous situation for reasons she can\'t explain, that she needs work. The Rivers siblings accept this, don\'t press for more information. They offer Jane a place to stay while she recovers and looks for employment. Jane has been saved—not just from death, but from complete isolation. She\'s found kindness, shelter, and potentially a new life. But she still thinks of Rochester constantly, still questions whether leaving was right choice, still carries the love and the loss that nearly killed her on the moors.'
    ]
  },
  
  // ===================================================================
  // TERMS TO KNOW
  // Literary devices, vocabulary words, and concepts crucial to understanding
  // ===================================================================
  termsToKnow: [
    {
      term: 'Leaving While They Sleep: The Necessary Escape',
      definition: 'When you must leave relationship/situation while person sleeps because seeing them again would break your resolve—recognizing your own vulnerability and protecting your decision by avoiding confrontation.',
      context: 'Jane leaves Thornfield while Rochester sleeps because she knows if she sees him again, her resolve might break. She loves him desperately; if he begs her to stay, if she sees his pain, she might give in. By leaving while he sleeps, she protects her decision—makes it impossible for him to change her mind. This isn\'t cowardice; it\'s self-knowledge. Jane recognizes she\'s vulnerable to Rochester\'s influence and takes steps to preserve the choice she\'s made.',
      whyItMatters: 'Sometimes maintaining a difficult decision requires avoiding situations that would undermine your resolve. When you know you\'re vulnerable to someone\'s influence (romantic partner, family member, employer), protecting your choice might mean leaving while they\'re absent, sending letter instead of talking face-to-face, having someone else communicate your decision. Modern contexts: leaving abusive relationship while partner is out, quitting job via email because face-to-face would pressure you to stay, ending relationship over phone because in-person would weaken resolve. Understanding this helps: (1) Recognize protecting your decision isn\'t cowardice—it\'s self-awareness, (2) If you can\'t maintain boundaries in person, creating distance is legitimate strategy, (3) Don\'t let guilt about "proper" way to leave prevent you from leaving, (4) Your safety and wellbeing matter more than someone else\'s preference for how you exit.'
    },
    {
      term: 'The Cost of Principle: When Doing Right Thing Nearly Kills You',
      definition: 'Experiencing severe material consequences for maintaining moral principles—discovering that being true to your values can cost you everything including your survival.',
      context: 'Jane left Rochester to maintain her integrity, and it nearly kills her. She wanders the moors starving, sleeping rough, begging for food, facing death from exposure. This is direct consequence of her moral choice: if she\'d stayed as Rochester\'s mistress, she\'d be safe, fed, housed. Instead she\'s dying on the moors. The novel doesn\'t romanticize this—Brontë shows the brutal reality that sometimes principle costs everything. Jane questions whether her choice was worth this suffering.',
      whyItMatters: 'Moral choices can have devastating material consequences. Sometimes being true to your principles means losing job, home, relationships, security—possibly facing genuine hardship or danger. Modern contexts: whistleblower who loses career and faces retaliation, person who leaves abusive but financially secure relationship and faces poverty, refugee who flees oppression and faces death in transit, employee who quits unethical job despite needing income. Understanding this helps: (1) Recognize moral courage often involves genuine sacrifice, (2) Have compassion for people who compromise principles to survive—the cost of doing "right thing" isn\'t always bearable, (3) Create safety nets so people can act ethically without dying (social support, legal protection for whistleblowers, resources for domestic violence survivors), (4) Acknowledge when your moral choices are possible because you have resources others lack.'
    },
    {
      term: 'Denied Charity: When No One Will Help Because You Look Desperate',
      definition: 'Being refused help precisely when you need it most because desperation makes you look suspicious, dangerous, or undeserving—the paradox that appearing to need help prevents you from receiving it.',
      context: 'Jane begs for work and food at farmhouses and shops, but everyone refuses. She has no references, looks desperate, appears suspicious. The more desperate she becomes (dirtier, hungrier, more exhausted), the less likely anyone is to help. Hannah at Moor House refuses to let her in—Jane looks like vagrant, possibly criminal or insane. The people most in need of charity are often least likely to receive it because their neediness makes them threatening or unworthy in others\' eyes.',
      whyItMatters: 'The appearance of desperation often prevents people from receiving help they need. When you look homeless, mentally ill, addicted, or extremely poor, people are more likely to refuse assistance because you seem dangerous or your situation seems hopeless. Modern contexts: homeless person refused service at restaurant because of appearance, job applicant passed over because gaps in resume suggest instability, person in crisis refused help because behavior seems erratic, refugee denied asylum because circumstances seem suspicious. Understanding this helps: (1) Recognize the cruel irony that those who most need help often can\'t access it, (2) Question your own assumptions about who "deserves" charity based on appearance, (3) Support systems that provide help without requiring people to look "worthy" or "deserving," (4) Understand that by the time someone looks desperate enough to frighten you, they\'ve been in crisis for a long time.'
    },
    {
      term: 'Questioning the Choice While Dying: Did I Do the Right Thing?',
      definition: 'Facing severe consequences of your decision and questioning whether maintaining principles was worth the cost—the agonizing uncertainty that comes when doing "right thing" leads to disaster.',
      context: 'As Jane starves on the moors, she questions whether leaving Rochester was right choice or terrible mistake. She\'s dying because she maintained her principles—would staying as his mistress really have been worse than this? She doesn\'t have comforting certainty that she did right thing; she has cold, hunger, and approaching death. The novel honestly portrays the doubt that accompanies costly moral choices: you can believe in your principles and still question whether they were worth dying for.',
      whyItMatters: 'Major moral choices often involve ongoing uncertainty, not confident righteousness. When you leave relationship to maintain integrity, quit job on principle, end friendship over values—and then face serious consequences—you\'ll likely question whether you made right choice. This doubt doesn\'t mean you were wrong; it means you\'re human and the choice was genuinely difficult. Modern contexts: whistleblower who loses career and questions whether speaking up was worth it, person who left secure but unethical situation and faces financial crisis, refugee who risked everything to escape and wonders if staying would have been safer. Understanding this helps: (1) Normalize questioning difficult choices even when you believe you did right thing, (2) Recognize doubt doesn\'t invalidate the moral reasoning behind your choice, (3) Understand that certainty isn\'t required for courage—you can be uncertain and still have made the right call, (4) Have compassion for your own doubt rather than demanding you feel heroically certain.'
    },
    {
      term: 'Found Family: Strangers Who Save You',
      definition: 'Being rescued by people who have no obligation to help you—strangers who see your need and respond with kindness, becoming the family/community you needed when biological family or previous connections failed.',
      context: 'The Rivers family saves Jane\'s life. They have no connection to her, no reason to take her in, limited resources themselves—but they see her dying on their doorstep and respond with compassion. They nurse her back to health, ask few questions, offer support without demanding explanations. This is found family: people who choose to care for you, who become your community not through blood or previous connection but through kindness and genuine care.',
      whyItMatters: 'Sometimes the people who save you are strangers who have no obligation but choose to help anyway. Found family—chosen relationships rather than biological ones—can provide support and belonging that biological family never did or can\'t anymore. Modern contexts: LGBTQ+ youth rejected by biological family finding chosen family in community, immigrants forming support networks with other immigrants, people recovering from trauma finding healing in support groups with strangers who understand. Understanding this helps: (1) Recognize family isn\'t only biological—chosen relationships can be equally or more meaningful, (2) Be the stranger who helps someone in crisis (you might be saving their life), (3) Accept help from unexpected sources—the people who save you might not be who you expected, (4) Build communities of mutual support rather than relying only on biological family who may not provide what you need.'
    }
  ],
  
  // ===================================================================
  // CHARACTERS
  // Character development for this chapter
  // ===================================================================
  characters: [
    {
      name: 'Jane Eyre',
      development: 'Jane faces the brutal consequences of her moral choice: starvation, exposure, near-death. She maintains her decision to leave Rochester even while dying on the moors, but she questions whether it was worth this cost. She\'s not heroically certain—she\'s cold, hungry, desperate, and doubting. When refused charity repeatedly, when collapsing at Moor House, she\'s at her absolute lowest point: no money, no shelter, no hope. Being saved by the Rivers family gives her chance to rebuild, but she carries Rochester with her—still loves him, still questions her choice, still grieves what she lost. This is Jane tested to her limit and surviving, but not easily or triumphantly.',
      keyTrait: {
        emoji: '🌙',
        text: 'Surviving the Cost of Principle'
      }
    },
    {
      name: 'St. John Rivers',
      development: 'St. John appears as Jane\'s rescuer: he finds her collapsed, overrides Hannah\'s objections, brings her inside, nurses her back to health. He\'s clergyman, serious and principled, with strong sense of duty. He offers help with few questions, respecting Jane\'s privacy while providing crucial support. St. John will become increasingly important to Jane\'s story—he offers her work, challenges her principles in new ways, eventually proposes marriage. But initially he\'s simply the person who saves her life when she\'s about to die.',
      keyTrait: {
        emoji: '⛪',
        text: 'Dutiful Rescuer'
      }
    },
    {
      name: 'Diana and Mary Rivers',
      development: 'Diana and Mary are Jane\'s first sight of Moor House through the window: two young women reading together, companionable and educated. When Jane is brought inside, they nurse her with kindness and ask few questions. They\'re governesses like Jane, understand the precarity of women\'s employment, sympathize with Jane\'s need for discretion. They offer genuine friendship—treating Jane as equal despite her desperate circumstances. Diana and Mary represent intellectual companionship Jane has craved.',
      keyTrait: {
        emoji: '📚',
        text: 'Kindred Spirits'
      }
    },
    {
      name: 'Hannah (Servant)',
      development: 'Hannah initially refuses to let Jane in—she sees desperate vagrant who might be dangerous, insane, or criminal. Hannah is protecting the household, doing her job, following reasonable caution. But her refusal nearly results in Jane\'s death. Hannah represents the way desperate appearance prevents people from receiving help. After Jane is taken in and recovers, Hannah feels guilty—she didn\'t realize how desperate Jane\'s situation was.',
      keyTrait: {
        emoji: '🚪',
        text: 'Cautious Gatekeeper'
      }
    },
    {
      name: 'Edward Rochester (Absent)',
      development: 'Rochester haunts this chapter though he never appears. Jane thinks of him constantly: wonders if he\'s searching for her, imagines his pain at her departure, questions whether leaving was right choice. Her love for him hasn\'t diminished—if anything, suffering on the moors intensifies her awareness of what she gave up. Rochester\'s absence is profound presence: he\'s the reason she\'s dying (because she left him) and the reason she questions whether maintaining principle was worth the cost.',
      keyTrait: {
        emoji: '👻',
        text: 'Haunting Absence'
      }
    }
  ],
  
  // ===================================================================
  // KEY QUOTES
  // 3-5 significant quotations with analysis
  // ===================================================================
  quotes: [
    {
      text: 'I rose, I dressed myself with care. I took my purse, containing twenty shillings; it was all I had. I quietly left my room and stole down the stairs. I would not see him again. If I did, my resolve would break.',
      analysis: 'Jane\'s departure shows strategic self-knowledge: she recognizes her vulnerability to Rochester and leaves while he sleeps to protect her decision. The detail "it was all I had" emphasizes the material cost—she\'s leaving with almost nothing, facing genuine danger. "If I did, my resolve would break" shows Jane knows herself: she loves Rochester desperately and can\'t trust herself to maintain boundaries face-to-face. This isn\'t cowardice; it\'s recognizing when you need to protect your choice by avoiding confrontation.'
    },
    {
      text: 'The coach drove on—I knew not where. When my money was exhausted, the driver left me at a crossroads. I stood alone, with no shelter, no food, no plan. This was the cost of my principles.',
      analysis: 'Brontë doesn\'t romanticize Jane\'s moral choice—she shows the brutal material consequences. Jane is literally abandoned at crossroads (symbolically apt: she made choice, now faces unknown future), with no resources, facing potential death. "This was the cost of my principles" is Jane\'s clear-eyed recognition: maintaining integrity has led to this desperate situation. The novel asks: is principle worth this cost? There\'s no easy answer.'
    },
    {
      text: 'I begged for work, for bread, for a night\'s shelter. All refused me. I had no references, looked desperate, appeared suspicious. The more I needed help, the less anyone would give it.',
      analysis: 'This captures the cruel paradox: the people who most need charity are often least likely to receive it because their desperation makes them threatening. Jane experiences this from the other side—she\'s now the suspicious vagrant people refuse. The observation "the more I needed help, the less anyone would give it" is social commentary on how neediness itself disqualifies people from receiving assistance. Those who look "respectable" get help; those who look desperate get refused.'
    },
    {
      text: 'I thought of him constantly. Was he searching for me? Did he grieve my departure? Had I been wrong to leave? Would life as his mistress truly have been worse than dying here on the moors?',
      analysis: 'Jane questions her choice while facing its consequences. She doesn\'t have heroic certainty—she has doubt, grief, and ongoing love for Rochester. The questions are genuine: maybe she was wrong? Maybe the life she refused would have been better than death? This doubt doesn\'t mean Jane made wrong choice; it shows the psychological reality that major moral decisions involve ongoing uncertainty, especially when you\'re suffering the consequences. You can believe in your principles and still question whether they were worth dying for.'
    },
    {
      text: 'Through the window I saw them: two young women reading together, faces peaceful and intelligent. I had nothing. They had everything I\'d lost: home, warmth, companionship, safety. I knocked. Please help me. I am dying.',
      analysis: 'Jane sees through the window what she\'s lost: not just material comfort but intellectual companionship, safety, belonging. The contrast between her desperate state (starving, exposed, about to die) and their comfortable domesticity emphasizes how far she\'s fallen. "I had nothing. They had everything I\'d lost" captures the devastation of her situation. The desperate plea "I am dying" is literal truth—she\'s about to die of exposure and starvation because she maintained her principles.'
    }
  ],
  
  // ===================================================================
  // IA ANALYSIS (Intelligence Amplifier Analysis)
  // Deep dive into themes and literary techniques
  // ===================================================================
  iaAnalysis: {
    themes: [
      {
        name: 'The Material Cost of Moral Principles',
        explanation: 'Jane maintains her integrity by leaving Rochester, and it nearly kills her. The novel doesn\'t romanticize this—Brontë shows the brutal reality that sometimes doing "right thing" has devastating material consequences. Jane faces starvation, exposure, potential death. She questions whether her choice was worth this cost. The theme explores: when principle requires sacrificing survival, what do you choose? Is integrity worth dying for? Jane\'s doubt (not heroic certainty) is the honest response to this impossible situation.'
      },
      {
        name: 'Found Family and Stranger\'s Kindness',
        explanation: 'The Rivers family saves Jane despite having no connection or obligation to her. They see a dying stranger and respond with compassion—providing shelter, nursing her to health, offering support without demanding explanations or payment. This is found family: chosen relationships rather than biological ones. Jane has no family (the Reeds rejected her), lost her romantic relationship (left Rochester), and is rescued by strangers who become her community. The theme demonstrates: family isn\'t only blood; sometimes the people who save you are strangers who choose to care.'
      },
      {
        name: 'Questioning Difficult Choices',
        explanation: 'As Jane suffers on the moors, she questions whether leaving Rochester was right choice or terrible mistake. She doesn\'t have confident certainty; she has doubt, cold, hunger, and approaching death. The theme shows: major moral choices involve ongoing uncertainty. You can believe you did right thing and still question whether it was worth the cost. Doubt doesn\'t invalidate the moral reasoning; it shows you\'re human and the choice was genuinely difficult. Jane\'s uncertainty is more honest than heroic confidence would be.'
      }
    ],
    
    literaryTechniques: [
      {
        name: 'Physical Suffering as External Manifestation of Internal Conflict',
        explanation: 'Brontë makes Jane\'s internal conflict (love for Rochester vs. commitment to principles) into external physical reality: she\'s literally dying from the consequences of her moral choice. The hunger, cold, and desperation externalize her internal state. By showing Jane\'s body breaking down from the cost of her principles, Brontë makes visible the psychological/spiritual struggle. This technique transforms abstract moral dilemma into concrete physical suffering, making the stakes vivid and immediate.',
        example: 'Jane wanders the moors starving: "I was so hungry I thought I would die. I was so cold I couldn\'t feel my hands. I collapsed, couldn\'t walk further." This physical suffering represents the internal cost of leaving Rochester—the emotional starvation, the coldness of being without love, the exhaustion of maintaining principles when every part of her wants to return. By making Jane\'s suffering physical and literal, Brontë shows readers the actual cost of moral courage rather than just telling them it was difficult.'
      },
      {
        name: 'Salvation Through Window: Visual Before Actual Connection',
        explanation: 'Jane sees the Rivers sisters through the window before meeting them: two women reading together, peaceful and companionable. This window-framed vision represents what Jane seeks—intellectual companionship, domestic peace, female friendship. She sees what she might have before she actually gains access to it. The window serves as both barrier (she\'s outside, desperate, excluded) and promise (this life could be hers). When she\'s finally admitted and becomes part of this household, the window scene is fulfilled—what she saw is what she receives.',
        example: 'Jane, dying and desperate, looks through window at Diana and Mary reading. She can see but not access this life. She knocks, is refused by Hannah, collapses. St. John finds her and brings her inside—literally crossing the threshold from outside (death, desperation, exclusion) to inside (life, safety, belonging). The window scene creates visual/symbolic representation of Jane\'s transition from isolation to found family, from death to rebirth. First she\'s voyeur looking in at life she can\'t have; then she becomes participant in that life.'
      },
      {
        name: 'Parallel Between Jane\'s Two Nadir Points',
        explanation: 'Brontë structures the novel with two lowest points for Jane: childhood at Gateshead/Lowood (orphan, abused, no power) and this moment on the moors (starving, homeless, about to die). Both times Jane is saved by intervention: first Miss Temple and then Helen\'s example help her survive Lowood; now the Rivers family saves her from death. The parallel shows Jane\'s resilience—she\'s been at bottom before and survived—while also showing each crisis is different. First time she was child with no agency; now she\'s adult who chose this situation by leaving Rochester. The parallel structures invite comparison: what has Jane gained between these two lowest points?',
        example: 'At Lowood: orphan child, powerless, suffering imposed by others (Mrs. Reed, Mr. Brocklehurst). On moors: adult woman, made her own choice, suffering is consequence of her moral agency. The difference: Jane chose this suffering to maintain integrity. At Lowood she was victim; on moors she\'s protagonist who made costly choice. The parallel shows Jane\'s growth—she now has agency even when that agency leads to suffering. She\'s no longer just acted upon; she acts, and accepts consequences. Both times she\'s saved by good people (Miss Temple then, Rivers family now), showing she also has capacity to inspire kindness in others.'
      }
    ]
  },
  
  // ===================================================================
  // MODERN ADAPTATION
  // Connect the classic text to contemporary life
  // ===================================================================
  modernAdaptation: {
    setting: 'Imagine you leave relationship/job/situation on principle—you believe staying would require compromising your fundamental values, so you choose to go despite having limited resources. You leave with savings that won\'t last long, no plan, nowhere to go. Family isn\'t option (estranged or unsupportive), friends can\'t help long-term, you need to start completely over. Your money runs out quickly. You try to find work but with no current references (can\'t use recent employer—what would they say?), gaps in resume, and increasingly desperate appearance (tired, stressed, wearing same clothes), no one will hire you. You couch-surf, then sleep in car, then can\'t afford that. You\'re hungry, exhausted, scared. You ask for help—most refuse because you look too desperate, suspicious, possibly unstable. You start questioning whether leaving was right choice: yes, you maintained your principles, but was integrity worth this suffering? Maybe compromising would have been better than homeless and starving? Just when you\'re about to become homeless statistic, someone helps: person/organization with no obligation takes you in, provides shelter and support without demanding full explanation of your situation. They offer practical help (place to stay, help finding work, basic resources) and treat you with dignity despite your desperate circumstances. You begin rebuilding: it\'s slow, difficult, you carry grief for what you lost, you still question whether your choice was right, but you\'re alive and have chance to start over.',
    
    parallels: [
      '🔹 **Leaving While They\'re Absent**: When maintaining difficult decision requires avoiding person who would undermine your resolve—leaving while they\'re out, communicating through third party, protecting your choice by not engaging face-to-face. Modern contexts: leaving abusive relationship while partner is away, quitting job via email, ending relationship over phone. Recognizing: this isn\'t cowardice, it\'s strategic self-protection.',
      '🔹 **Material Consequences of Moral Choices**: When doing "right thing" costs you security, shelter, income, relationships—discovering principle can require sacrificing survival needs. Modern contexts: whistleblower losing career, person leaving unethical but lucrative job, refugee fleeing oppression, domestic violence survivor leaving financial security. Understanding: moral courage often involves genuine material cost.',
      '🔹 **Looking Too Desperate for Help**: Being refused assistance because your neediness makes you appear suspicious or undeserving—the paradox that appearing to need help prevents receiving it. Modern contexts: homeless person refused service, desperate job seeker passed over, person in crisis seeming "too much" for friends/family. Recognizing: those who look most desperate often need help most.',
      '🔹 **Questioning Your Choice While Suffering**: Facing severe consequences and wondering whether maintaining principles was worth the cost—ongoing doubt about whether you made right decision. Modern contexts: whistleblower who lost everything questioning if speaking up was worth it, person who left relationship on principle wondering if they should have stayed. Understanding: doubt doesn\'t mean you were wrong; it means choice was genuinely difficult.',
      '🔹 **Found Family and Stranger\'s Kindness**: Being saved by people who have no obligation—strangers who choose to help, becoming the community you need. Modern contexts: LGBTQ+ youth finding chosen family after biological family rejects them, immigrants forming support networks, support groups of strangers who understand. Recognizing: family isn\'t only biological; chosen relationships can save your life.',
      '🔹 **Pride vs. Survival**: Struggling with whether to ask for help, accept charity, or compromise on what you thought were minimum standards—discovering that survival sometimes requires setting aside pride. Modern contexts: using food bank, accepting public assistance, moving back with parents, taking job "beneath" your qualifications. Learning: survival isn\'t failure; sometimes accepting help is courage.',
      '🔹 **Rebuilding from Nothing**: Starting over with no resources, no references, no network—the overwhelming task of reconstructing your life when you\'ve lost everything. Modern contexts: leaving abusive situation with nothing, starting over after incarceration, rebuilding after addiction/mental health crisis. Understanding: rebuilding is slow, nonlinear, requires help, and carrying grief for what you lost doesn\'t mean you regret your choice.'
    ],
    
    discussionPrompt: 'Have you left situation on principle and faced severe material consequences? How did you survive? Have you questioned whether maintaining your values was worth the cost? Have you been refused help when you needed it most because you appeared too desperate? Have you been saved by stranger\'s kindness—someone with no obligation who chose to help? Have you had to rebuild from nothing? What did that process teach you about survival, community, and moral choices?'
  },
  
  // ===================================================================
  // THEMATIC THREADS
  // Ongoing themes that recur throughout the novel
  // ===================================================================
  thematicThreads: [
    {
      emoji: '💀',
      name: 'Near-Death as Transformation Point',
      explanation: 'Jane comes close to death on the moors—this is rock bottom, absolute lowest point. But surviving this near-death experience transforms her: she\'s proven she can maintain principles even when they cost everything, she\'s lost everything and survived, she\'s been forced to accept help from strangers. The near-death experience strips away everything except her core self, and what remains is strong enough to rebuild from nothing.'
    },
    {
      emoji: '🏡',
      name: 'Home as What You Create, Not What You\'re Born Into',
      explanation: 'Jane has no biological family home (Reeds rejected her), lost Thornfield (left Rochester), and now finds home with the Rivers—strangers who become family through choice and kindness. The thread shows: home isn\'t where you\'re born or where you have biological ties; it\'s where you\'re accepted, where you belong, where people choose to love you. Found family can provide the home biological family never did.'
    },
    {
      emoji: '🔄',
      name: 'Parallel Lowest Points: Growth Through Repetition',
      explanation: 'Jane experiences similar lowest point as at Lowood—destitute, powerless, near death. But crucial difference: at Lowood she was child victim; on moors she\'s adult who made choice that led here. The parallel shows her growth: she now has agency even when agency leads to suffering. She\'s no longer only acted upon; she acts, accepts consequences, survives anyway. Each lowest point tests her differently.'
    },
    {
      emoji: '❓',
      name: 'Doubt as Part of Courage',
      explanation: 'Jane questions whether leaving Rochester was right choice—she doesn\'t have heroic certainty while suffering on moors. This doubt is realistic and honest: major moral choices involve ongoing uncertainty. Courage isn\'t feeling confident you\'re right; it\'s maintaining your choice despite doubt, paying the cost despite questioning whether it\'s worth it. Jane\'s uncertainty makes her choice more courageous, not less.'
    },
    {
      emoji: '🤝',
      name: 'Kindness of Strangers vs. Cruelty of Family',
      explanation: 'Jane\'s biological family (Reeds) were cruel; strangers (Miss Temple, Rivers family) save her. The thread inverts expectation that family will care for you and strangers are dangerous: often it\'s opposite. The people who have no obligation (strangers who choose to help) provide better care than those who are "supposed" to (biological family who reject you). This validates chosen family and stranger\'s kindness as legitimate forms of love and care.'
    }
  ],
  
  // ===================================================================
  // DISCUSSION QUESTIONS
  // Open-ended questions for classroom or personal reflection
  // ===================================================================
  discussionQuestions: [
    {
      title: 'Was Jane\'s Choice Worth the Cost?',
      question: 'Jane maintains her principles by leaving Rochester, and it nearly kills her. She faces starvation, exposure, and near-death. In retrospect, was her moral choice worth this cost? Would staying as Rochester\'s mistress have been worse than almost dying on the moors? How do we evaluate whether principle is worth potential death? Is there point where survival should override principles?'
    },
    {
      title: 'Leaving While They Sleep',
      question: 'Jane leaves Thornfield while Rochester sleeps because she knows if she sees him again her resolve will break. Is this wise self-protection or cowardly avoidance? When is it appropriate to protect your decision by avoiding confrontation vs. when do you owe someone face-to-face conversation? Does the power dynamic (Rochester could pressure Jane to stay) justify her departure while he sleeps?'
    },
    {
      title: 'Denied Charity',
      question: 'Jane is refused help repeatedly because she looks desperate and suspicious—the more she needs help, the less likely people are to give it. Why do people refuse to help those who appear most desperate? What makes someone seem "deserving" vs. "undeserving" of charity? How do we balance legitimate caution (Hannah protecting household) with moral obligation to help those in need?'
    },
    {
      title: 'Questioning Your Choice',
      question: 'Jane questions whether leaving Rochester was right choice while she\'s suffering the consequences. Does doubt mean she was wrong? Can you make right choice and still question whether it was worth the cost? How do we distinguish between legitimate doubt (maybe I made wrong call) and natural human response to suffering (this is hard, was it worth it)?'
    },
    {
      title: 'Found Family',
      question: 'The Rivers family saves Jane despite having no connection to her—they become her found family. What makes these chosen relationships as or more meaningful than biological family? When biological family fails or rejects you, is it okay to create new family with strangers who choose to care? What obligations do we have to biological family vs. chosen family?'
    },
    {
      title: 'Pride vs. Survival',
      question: 'Jane struggles with begging and accepting charity—her pride makes it difficult to ask for help even when dying. When does pride become obstacle to survival? Is there dignity in accepting help, or does dependence on charity diminish you? How do we balance maintaining self-respect with accepting assistance we need to survive?'
    },
    {
      title: 'The Window Scene',
      question: 'Jane looks through window at Diana and Mary reading together—sees domestic peace and intellectual companionship she\'s lost. Why does Brontë show Jane observing before participating? What does the window represent—barrier, promise, glimpse of possible future? When Jane is finally admitted and becomes part of this household, how has crossing that threshold transformed her?'
    }
  ],
  
  // ===================================================================
  // AMPLIFIED DISCUSSION
  // Deep-dive answers to complex questions
  // ===================================================================
  amplifiedDiscussion: [],
  
  // ===================================================================
  // EDUCATOR RESOURCES
  // Practical classroom tools
  // ===================================================================
  educatorResources: {
    writingPrompt: {
      title: 'Analyzing the Material Cost of Moral Choices: When Principle Requires Sacrifice',
      description: 'Write an analytical essay examining the material consequences of moral choices, using Jane\'s near-death on the moors as case study and connecting to contemporary contexts. Part 1: Analyze Jane\'s situation: She chose integrity over survival (left Rochester to maintain principles), faced devastating material consequences (starvation, exposure, near-death), questioned whether choice was worth the cost (ongoing doubt while suffering), survived through stranger\'s intervention (would have died without Rivers family). Map: (A) What Jane sacrificed to maintain principles (safety, shelter, food, relationship, home, companionship), (B) What she preserved (moral integrity, self-respect, sense of self as person who maintains principles), (C) Whether the preservation justified the sacrifice. Part 2: Examine different philosophical approaches to situations where principle conflicts with survival. Approach A: Principle should always be maintained regardless of cost (deontological ethics—some things are always wrong even if consequences are terrible). Approach B: Survival takes precedence when choice is between life and principle (consequentialist ethics—outcomes matter more than abstract principles). Approach C: Context matters (virtue ethics—consider particular circumstances, relationships, what kind of person you want to be). Apply each to Jane: Should she have stayed with Rochester to survive? Part 3: Connect to contemporary contexts where moral choices have material costs: (A) Whistleblower who loses career and faces retaliation, (B) Person who quits unethical but lucrative job despite needing income, (C) Domestic violence survivor who leaves financial security for safety, (D) Refugee who risks death fleeing oppression, (E) Employee who reports discrimination knowing they might be fired. For each, analyze: What\'s at stake? What would principle require? What would survival require? How do we judge people who choose differently? Part 4: Develop position: Under what circumstances should principle override survival? When is compromise justified? How do we have compassion for those who compromise while respecting those who don\'t? Consider: Does your position assume resources/safety net that makes principled choice possible? Would answer change if you were actually facing death vs. theoretically considering it?',
      purpose: 'This prompt develops sophisticated moral reasoning about situations where ethics and survival conflict—moving beyond simple "always be principled" to grappling with genuine difficulty when maintaining principles might cost your life or safety. Students analyze Jane\'s choice without assuming there\'s easy "right" answer, consider philosophical frameworks for evaluating when principle should override survival, connect to real contemporary situations where people face these impossible choices. Connects to crucial understanding: moral courage often requires material sacrifice, and judging others\' choices requires recognizing our own privilege if we have resources that make principled stance possible. Students learn: (1) How to analyze cost-benefit of moral choices honestly rather than assuming principle always wins, (2) Different ethical frameworks for situations where principle conflicts with survival, (3) Compassion for people who compromise to survive (sometimes that\'s the only viable choice), (4) Recognition that ability to maintain principles often depends on having resources/safety net.'
    },
    
    activity: {
      title: 'Survival Simulation: Resource Mapping and Decision Trees',
      description: 'Students work through scenario similar to Jane\'s to understand material realities of maintaining principles when resources are limited. Setup: Divide class into groups. Each group receives scenario: "You\'ve left job/relationship/situation on principle. You have $200, no current references (previous employer/partner would give bad reference if asked), no family support. Map resources and decisions." Activity proceeds through stages: Stage 1: Resource Inventory. Groups map: (A) What you need for basic survival (shelter, food, transportation, hygiene, clothing for job interviews), (B) How long $200 lasts if you\'re careful (calculate: cheap room, minimal food, bus fare to job interviews), (C) What happens when money runs out in 1-2 weeks. Stage 2: Job Search Reality. Groups consider: Without current reference, gaps in resume, increasingly desperate appearance as money runs out—who will hire you? Research: what jobs available without references? How long does hiring process take? Do you have resources to wait? Stage 3: Help-Seeking Decisions. Groups evaluate: (A) Pride vs. survival (when do you ask family for help despite estrangement? when do you use food bank? when do you accept charity?), (B) Compromising principles (would taking job with previous employer you left on principle be "giving up" or "surviving"?), (C) What help is available and how to access it (research local resources: shelters, food assistance, job training, social services). Stage 4: Decision Trees. Each group creates decision tree showing: if money runs out and still no job, what options exist? For each option, map: consequences (practical and emotional), resources required, likelihood of success, cost to principles vs. cost to survival. Stage 5: Debrief. Groups present their decision trees and discuss: How quickly did resources run out? How many "good" options existed vs. choice between bad options? What assumptions did you make about available help? Did you find yourself compromising principles you thought were absolute? How did facing survival choices change your judgment of people who compromise? Connect to Jane: She faced exactly this—left on principle, resources ran out, almost died, saved by strangers. Without Rivers family, she\'d have died maintaining her principles. Does that make her choice wrong, or does it show how desperately we need better social safety nets so people can act ethically without dying?',
      materials: 'Budget worksheets, resource research guides, local services directories, decision tree templates, survival scenario cards, ethical frameworks handouts'
    },
    
    crossCurricular: {
      title: 'Sociology/Economics: Poverty, Homelessness, and Access to Charity',
      description: 'Partner with sociology/economics to examine structural realities of poverty and homelessness that Jane experiences, understanding barriers to accessing help. Sociology class covers: (1) Who becomes homeless (domestic violence survivors, people with gaps in employment, those without family safety nets, youth rejected by families, people fleeing abusive situations), (2) Barriers to accessing help (appearance-based discrimination, requirement for ID/documentation, available shelter space, stigma, bureaucratic obstacles), (3) "Deserving" vs. "undeserving" poor (historical concept that some poor people deserve help while others don\'t, based on judgments about their behavior/choices), (4) How desperation prevents help (the paradox that looking desperate makes people less likely to assist). Economics class examines: (A) Cost of survival (how much money needed for basic necessities, how quickly resources deplete, poverty line vs. actual cost of living), (B) Job market realities (difficulty getting hired without current references, gaps in resume, time lag between application and employment), (C) Economic vulnerability of women (gender pay gap, women\'s jobs often precarious, economic dependence in relationships), (D) Safety nets (which exist, who can access them, what they provide vs. what people need). English class analyzes Jane Eyre through this lens: Jane left on principle and nearly died because she had no safety net—no family, no savings, no references, no resources. Understanding structural realities shows why her choice was so costly: not just because she left Rochester but because society provides no support for women in her position. Final project: Students research contemporary issues: (1) What resources exist for people leaving abusive relationships? Are they adequate? (2) What barriers do homeless people face accessing shelter/food/services? (3) How do "deserving poor" narratives still operate today? (4) What would adequate safety net look like—what would have saved Jane from near-death? Students write proposals: If you were designing social support system, what would you include to allow people to leave bad situations without risking death? Extension: Compare countries with different social safety nets—how does availability of resources affect people\'s ability to leave bad situations? Connect to broader question: Should society provide supports that allow people to act ethically (leave abusive situations, quit unethical jobs, maintain principles) without dying?',
      subjects: ['Sociology', 'Economics', 'Social Work', 'Public Policy', 'Ethics', 'Gender Studies']
    }
  },
  
  // ===================================================================
  // CRITICAL THINKING EXERCISE
  // One focused, high-level analytical task
  // ===================================================================
  criticalThinkingExercise: {
    title: 'Evaluating When Principle Should Override Survival: Philosophical Frameworks Applied',
    prompt: 'Jane chooses principle (leaving Rochester to maintain integrity) over survival (staying would provide safety, food, shelter), and nearly dies as result. Your task: Develop philosophical framework for evaluating when principle should override survival considerations, and when compromise for survival is justified. Consider: (1) Are some principles worth dying for? If so, which ones and why? (2) Is ability to maintain principles often dependent on having resources/safety net? (3) How do we judge people who choose differently—those who maintain principles vs. those who compromise to survive? (4) What responsibilities does society have to create conditions where people can act ethically without risking death?',
    
    guidingQuestions: [
      'Analyze Jane\'s choice through cost-benefit framework. Costs of leaving: (1) Physical survival threatened (starvation, exposure, near-death), (2) Emotional suffering (grief at losing Rochester, loneliness, questioning her choice), (3) Material loss (home, security, comfort), (4) Social isolation (no connections, no community). Benefits of leaving: (1) Moral integrity maintained (didn\'t become mistress, didn\'t compromise principles), (2) Self-respect preserved (remains person she can respect), (3) Legal innocence (not living in bigamous relationship), (4) Long-term self-preservation (avoided becoming completely dependent on man who already proved he\'ll deceive her). On balance, do benefits justify costs? Is this calculation even appropriate—can you weigh integrity against survival? Does framing it as cost-benefit miss something important about moral choices?',
      'Examine through different ethical frameworks. Framework 1: Deontological ethics (Kant): Some actions are always wrong regardless of consequences. By this framework, becoming mistress to married man is wrong even if alternative is death—principle matters more than outcome. Jane\'s choice is morally correct even though it nearly killed her. Framework 2: Consequentialist ethics (Mill): Rightness of action depends on consequences. By this framework, dying on moors for abstract principle when she could have lived safely as mistress produces worse outcome—survival matters more than abstract morality. Jane\'s choice led to suffering without clear benefit, therefore questionable. Framework 3: Virtue ethics (Aristotle): Consider what kind of person you want to be and what particular circumstances require. By this framework, maintaining integrity is part of being virtuous person Jane wants to be, but virtue also includes practical wisdom about when to flex vs. when to hold firm. Which framework best evaluates Jane\'s situation? Or does each capture some truth?',
      'Consider role of resources and privilege in moral choices. Jane almost died because she had no safety net: no family to return to, no savings, no connections, no resources. If she\'d had wealthy family or substantial savings, maintaining principles wouldn\'t have nearly killed her. Questions: (A) Is ability to maintain principles often function of having resources? (B) When we admire people who maintain principles despite cost, are we sometimes admiring the privilege that made that choice survivable? (C) Do we judge differently people who compromise to survive (they should have been more principled) vs. people who maintain principles (they\'re heroes), without recognizing that resources often determine which choice is possible? (D) Is it fair to expect people without resources to maintain principles that might kill them, when people with resources can maintain same principles safely?',
      'Evaluate what society owes to make ethical choices possible. Jane nearly died because Victorian society provided no support for women in her situation: she couldn\'t return to family (estranged), couldn\'t get hired (no current references, gaps in employment), couldn\'t access charity (appearance-based discrimination), had no social safety net. Consider: (A) If we believe people should act ethically (Jane was right to leave Rochester), do we have obligation to create conditions where ethical actions don\'t result in death? (B) What safety nets would have allowed Jane to maintain principles without nearly dying? (food assistance, shelter, job placement, social services for women leaving difficult situations), (C) Is it moral to expect people to uphold principles when society provides no support for those who do?, (D) Connection to contemporary contexts: Should we provide robust support for whistleblowers (so people can report wrongdoing without losing livelihood)? Domestic violence survivors (so people can leave abuse without becoming homeless)? People quitting unethical jobs (so acting ethically doesn\'t mean starvation)?',
      'Develop nuanced position on when principle should override survival. Consider different scenarios: Scenario A: Person faces minor inconvenience for maintaining principle (some discomfort, social awkwardness, losing friendship). Should maintain principle—cost is bearable. Scenario B: Person faces significant hardship but not death (job loss, temporary poverty, starting over). Harder choice—depends on severity of principle violation and availability of resources to survive hardship. Scenario C: Person faces genuine threat to survival (will be homeless, will starve, will die). Hardest choice—principle matters but so does survival; answer depends on multiple factors (which principle? what alternatives exist? is there safety net?). Apply framework: For which principles would you risk death? For which would you compromise to survive? How do resources affect your answer? If you had wealth/family support, would you judge differently than if you had nothing?'
    ],
    
    thinkingFramework: {
      analyze: 'Analyze situations where principle conflicts with survival through systematic matrix. Dimension 1: Severity of principle at stake. (A) Principles protecting fundamental rights/preventing serious harm (don\'t participate in genocide, don\'t enslave others, don\'t abuse children): These should almost always be maintained even at personal cost—the harm prevented is so severe that personal survival doesn\'t justify participation. (B) Principles about personal integrity without harming others (don\'t lie, don\'t become mistress to married man, don\'t work for unethical company): These matter for your moral character but don\'t prevent severe harm to others—harder to justify dying for them, though maintaining them is admirable. (C) Principles about social conventions (don\'t cohabitate before marriage, don\'t work on Sabbath, don\'t associate with certain groups): These often reflect cultural norms more than universal ethics—least justified to die for, most appropriate to flex when survival is at stake. Jane\'s principle (don\'t become mistress) is Type B: matters for her integrity, doesn\'t directly harm others, falls in difficult middle ground. Dimension 2: Severity of survival threat. (1) Genuine threat to life (will die without compromise): Highest cost—requires strongest justification for maintaining principle. (2) Severe hardship but not death (homelessness, poverty, but survival possible): Significant cost—principle matters but survival is achievable, if difficult. (3) Discomfort but basic needs met (social stigma, awkwardness, inconvenience): Lowest cost—should maintain principle because survival isn\'t threatened. Jane faces Threat 1: she\'s literally dying on moors—genuine threat to life. Dimension 3: Availability of alternatives and resources. (X) No alternatives and no resources: Most severe—compromise or die are only options. (Y) Limited alternatives with significant cost: Difficult—some paths to survival exist but require major sacrifice. (Z) Multiple alternatives or safety net exists: Least severe—can maintain principle without dying because resources/support available. Jane has Situation X: no family, no money, no references, no support—compromise or die were her only options until Rivers family intervened. Synthesize: Jane maintained Type B principle (personal integrity, doesn\'t prevent harm to others) despite Type 1 threat (genuine risk of death) in Situation X (no alternatives/resources). This is ambiguous situation: admirable that she maintained integrity even when it nearly killed her, but also questionable whether personal integrity principle justifies risking death when you have no safety net. Different people will evaluate differently based on their ethical framework.',
      evaluate: 'Evaluate through multiple lenses, acknowledging complexity. Lens 1: Jane as moral hero. She maintained integrity despite immense cost (near-death), didn\'t compromise principles even when dying, survived through strength of character and fortunate intervention. From this lens: some principles are worth dying for, and maintaining integrity even at cost of survival is highest form of moral courage. Jane did right thing even though it nearly killed her. Celebrate this courage. Lens 2: Jane as person shaped by limited options. Victorian society gave her almost no alternatives: couldn\'t divorce (not legal grounds), couldn\'t access social support (none existed), couldn\'t rely on family (estranged), couldn\'t get hired (no references). From this lens: Jane\'s near-death isn\'t testament to her moral courage so much as indictment of society that provides no support for women leaving difficult situations. The question isn\'t whether Jane was right to maintain principles but why maintaining principles required nearly dying—society failed her. Lens 3: Jane as person making privileged choice. She had privilege of education (could work as governess), youth and health (could physically survive moors for days), and luck (Rivers family found her). From this lens: many people in her situation would have died—she survived partly through advantages. Others without her education, health, or luck would have been unable to maintain principles because doing so would have killed them. Acknowledging this complicates the "maintain principles regardless" narrative. Lens 4: Jane as person making rational calculation. Staying with Rochester meant becoming completely dependent on man who already proved he\'ll deceive her—no legal protection, no social standing, could be abandoned anytime. From this lens: Jane wasn\'t just maintaining abstract principle; she was protecting herself from very real danger of complete vulnerability to untrustworthy person. Her "principled" choice was also practical risk assessment—being his mistress might have been worse long-term than risk of death short-term. Most sophisticated understanding: elements of all four lenses are true. Jane made morally courageous choice (Lens 1) in society that provided no support (Lens 2) with privileges that made survival possible (Lens 3) while also rationally assessing her options (Lens 4). The complexity is irreducible—there\'s no simple "right" answer to whether she should have stayed vs. left.',
      synthesize: 'Synthesize framework for evaluating when principle should override survival. Step 1: Assess the principle. Question: Which category does this principle fall into? (A) Preventing serious harm to others (almost always maintain), (B) Personal integrity without harming others (maintain when possible, context-dependent when survival threatened), (C) Social convention without clear moral content (reasonable to compromise for survival). Step 2: Assess the threat. Question: How severe is the survival threat? (1) Genuine risk of death (highest threat—requires strongest justification for maintaining principle), (2) Severe hardship (significant threat—principle matters but survival is achievable), (3) Discomfort only (minor threat—maintain principle). Step 3: Assess alternatives and resources. Question: What options and support exist? (X) No alternatives, no safety net (most severe—compromise or die), (Y) Limited alternatives with cost (difficult—some paths exist), (Z) Multiple options or support available (least severe—can maintain principle without dying). Step 4: Make decision recognizing values at stake. Decision matrix: For Category A principles (prevent harm) + Threat 1 (death) + Situation X (no alternatives): Maintain principle even at cost of life—preventing serious harm to others justifies personal sacrifice. For Category B principles (personal integrity) + Threat 1 (death) + Situation X (no alternatives): Genuinely difficult choice—neither compromising nor maintaining principle is clearly "right." Depends on: which principles are core to your identity? can you live with yourself if you compromise? can you justify risking death for principle that doesn\'t prevent harm to others? For Category C principles (social convention) + any threat + any situation: Compromise justified—social conventions aren\'t worth dying for. Step 5: After making choice, recognize: (1) You might question it forever (doubt doesn\'t mean you were wrong), (2) Others might judge you either way (some will say you should have compromised, some will say you were right), (3) Your ability to maintain principles often depends on resources you have (privilege matters), (4) Society should provide safety nets so ethical choices don\'t require death (individual moral courage shouldn\'t require societal neglect). Apply broadly: When facing choice between principle and survival, assess systematically: Which principles? How severe is threat? What resources exist? Make choice recognizing complexity, have compassion for yourself and others navigating these impossible situations, and work toward society that doesn\'t force people to choose between ethics and survival.'
    },
    
    expectedDepth: 'Strong responses will: (1) Analyze Jane\'s choice through cost-benefit framework while questioning whether that framing is appropriate for moral decisions; (2) Apply multiple ethical frameworks (deontological, consequentialist, virtue ethics) and recognize each captures some truth; (3) Grapple with role of resources and privilege—acknowledging Jane\'s ability to maintain principles depended partly on advantages and luck; (4) Consider societal obligations to create safety nets that allow ethical choices without death; (5) Distinguish between different types of principles (preventing harm vs. personal integrity vs. social convention) and different severities of threat (death vs. hardship vs. discomfort); (6) Recognize Jane\'s "principled" stance also had practical element—protecting herself from complete dependence on deceiver; (7) Develop nuanced framework that avoids both "always maintain principles regardless" absolutism and "survival always justifies compromise" relativism; (8) Apply framework to contemporary contexts (whistleblowers, domestic violence survivors, people quitting unethical jobs); (9) Acknowledge genuine difficulty and ongoing uncertainty—Jane questions her choice while dying, and that doubt is honest response to impossible situation; (10) Synthesize sophisticated position: Some principles worth dying for (preventing serious harm), some worth significant sacrifice (personal integrity), some not worth death (social conventions), and answer always depends on severity of threat and availability of alternatives. Excellent responses will meta-analyze: recognize that ability to maintain principles often depends on having resources/safety net, and therefore we should both admire moral courage AND work to create conditions where ethical choices don\'t require death. Jane\'s near-death is both testament to her courage and indictment of society that provides no support.',
    
    classroomApplication: 'Works as: (1) Analytical essay (15-20 pages) examining when principle should override survival through philosophical frameworks, Jane Eyre case study, and contemporary applications; (2) Debate: "Jane should have stayed with Rochester because survival matters more than abstract principles" (argue for: consequentialism, practical realities, severity of death threat; argue against: deontological ethics, personal integrity, long-term dangers of dependence on deceiver); (3) Case study analysis: present scenarios where people face principle vs. survival choices (whistleblower who will lose career, person fleeing abuse who will face poverty, employee quitting unethical job who needs income), students develop recommendations using framework; (4) Moral dilemma simulation: students work through scenarios with escalating costs for maintaining principles, identify at what point they would compromise; (5) Policy development: design social safety nets that would allow people to maintain principles without dying—what supports should exist? Time: 8-10 class periods including ethical theory, Jane Eyre analysis, contemporary contexts, framework development, applications. Connect to: philosophy (ethical frameworks), sociology (poverty, homelessness, barriers to help), economics (cost of survival, job market realities), policy (safety nets and their design), history (Victorian social support vs. contemporary), psychology (moral decision-making under duress). Consider inviting: ethicist to discuss principle vs. survival dilemmas, social worker to explain barriers people face accessing help, domestic violence counselor to discuss challenges of leaving abusive situations, whistleblower or activist who maintained principles at significant cost. Extension: Research actual outcomes for people who maintained principles vs. compromised in various contexts—does maintaining principles usually lead to positive outcomes? Or do we hear survivor stories but not stories of those who didn\'t survive? What survivorship bias might exist in narratives about moral courage? Final reflection: What are your core principles? Under what circumstances would you risk death for them? If you wouldn\'t risk death, does that mean they\'re not really principles? Or does it mean you\'re practical about survival? How do you distinguish between moral courage and privileged ability to maintain principles because you have safety net?'
  },
  
  // ===================================================================
  // WHY LITERATURE MATTERS
  // Rotating message about literature's importance (auto-rotated by chapter number)
  // ===================================================================
  whyLiteratureMatters: getLiteratureMessageByChapter(26),
  
  // ===================================================================
  // NEXT TIME TEASER
  // Preview of next chapter to build anticipation
  // ===================================================================
  nextTimeTeaser: {
    emoji: '🏫📖',
    title: 'Next Time: Chapter 27 — New Life at Moor House',
    preview: 'Jane recovers and begins new life with the Rivers family. St. John finds her work teaching at a village school—humble position teaching poor children, vastly different from her governess role at Thornfield, but honest employment that allows her independence. Jane accepts, choosing meaningful work over status. She grows close to Diana and Mary, finding the intellectual companionship and female friendship she\'s always wanted. But she still thinks constantly of Rochester—wonders how he\'s coping with her departure, whether he\'s searching for her, if she\'ll ever see him again. St. John is increasingly important in her life: he\'s impressive—learned, dedicated, strong-willed—but also cold, rigid, fanatical about duty. He sees Jane\'s strength and begins to view her as potential helpmate for his missionary ambitions. Meanwhile, Jane receives shocking news: her uncle John Eyre has died and left her a fortune—she\'s now wealthy and financially independent. But the inheritance comes with revelation: the Rivers siblings are her cousins—they\'re family she never knew she had. Jane insists on sharing the inheritance equally with her newly discovered cousins. Finally she has family, community, independence, and security. But she still loves Rochester, still wonders about him, and when St. John proposes marriage (not from love but from duty, wanting her as missionary partner), Jane must decide: accept loveless but purposeful marriage, or risk everything to find Rochester and discover if reconciliation is possible.',
    hookQuestion: 'Will Jane accept St. John\'s proposal of duty over love? Or will she return to Rochester despite not knowing how he\'s responded to her departure? Can she balance her newfound independence with her enduring love for the man she left?'
  }
}

